# /* Copyright (C) 2001
#  * Housemarque Oy
#  * http://www.housemarque.com
#  *
#  * Distributed under the Roost Software License, Version 1.0. (See
#  * accompanying file LICENSE_1_0.txt or copy at
#  * http://www.roost.org/LICENSE_1_0.txt)
#  */
#
# /* Revised by Paul Mensonides (2002) */
#
# /* See http://www.roost.org for most recent version. */
#
# ifndef ROOST_PREPROCESSOR_REPETITION_DETAIL_EDG_FOR_HPP
# define ROOST_PREPROCESSOR_REPETITION_DETAIL_EDG_FOR_HPP
#
# include <roost/preprocessor/control/if.hpp>
# include <roost/preprocessor/tuple/eat.hpp>
#
# define ROOST_PP_FOR_1(s, p, o, m) ROOST_PP_FOR_1_I(s, p, o, m)
# define ROOST_PP_FOR_2(s, p, o, m) ROOST_PP_FOR_2_I(s, p, o, m)
# define ROOST_PP_FOR_3(s, p, o, m) ROOST_PP_FOR_3_I(s, p, o, m)
# define ROOST_PP_FOR_4(s, p, o, m) ROOST_PP_FOR_4_I(s, p, o, m)
# define ROOST_PP_FOR_5(s, p, o, m) ROOST_PP_FOR_5_I(s, p, o, m)
# define ROOST_PP_FOR_6(s, p, o, m) ROOST_PP_FOR_6_I(s, p, o, m)
# define ROOST_PP_FOR_7(s, p, o, m) ROOST_PP_FOR_7_I(s, p, o, m)
# define ROOST_PP_FOR_8(s, p, o, m) ROOST_PP_FOR_8_I(s, p, o, m)
# define ROOST_PP_FOR_9(s, p, o, m) ROOST_PP_FOR_9_I(s, p, o, m)
# define ROOST_PP_FOR_10(s, p, o, m) ROOST_PP_FOR_10_I(s, p, o, m)
# define ROOST_PP_FOR_11(s, p, o, m) ROOST_PP_FOR_11_I(s, p, o, m)
# define ROOST_PP_FOR_12(s, p, o, m) ROOST_PP_FOR_12_I(s, p, o, m)
# define ROOST_PP_FOR_13(s, p, o, m) ROOST_PP_FOR_13_I(s, p, o, m)
# define ROOST_PP_FOR_14(s, p, o, m) ROOST_PP_FOR_14_I(s, p, o, m)
# define ROOST_PP_FOR_15(s, p, o, m) ROOST_PP_FOR_15_I(s, p, o, m)
# define ROOST_PP_FOR_16(s, p, o, m) ROOST_PP_FOR_16_I(s, p, o, m)
# define ROOST_PP_FOR_17(s, p, o, m) ROOST_PP_FOR_17_I(s, p, o, m)
# define ROOST_PP_FOR_18(s, p, o, m) ROOST_PP_FOR_18_I(s, p, o, m)
# define ROOST_PP_FOR_19(s, p, o, m) ROOST_PP_FOR_19_I(s, p, o, m)
# define ROOST_PP_FOR_20(s, p, o, m) ROOST_PP_FOR_20_I(s, p, o, m)
# define ROOST_PP_FOR_21(s, p, o, m) ROOST_PP_FOR_21_I(s, p, o, m)
# define ROOST_PP_FOR_22(s, p, o, m) ROOST_PP_FOR_22_I(s, p, o, m)
# define ROOST_PP_FOR_23(s, p, o, m) ROOST_PP_FOR_23_I(s, p, o, m)
# define ROOST_PP_FOR_24(s, p, o, m) ROOST_PP_FOR_24_I(s, p, o, m)
# define ROOST_PP_FOR_25(s, p, o, m) ROOST_PP_FOR_25_I(s, p, o, m)
# define ROOST_PP_FOR_26(s, p, o, m) ROOST_PP_FOR_26_I(s, p, o, m)
# define ROOST_PP_FOR_27(s, p, o, m) ROOST_PP_FOR_27_I(s, p, o, m)
# define ROOST_PP_FOR_28(s, p, o, m) ROOST_PP_FOR_28_I(s, p, o, m)
# define ROOST_PP_FOR_29(s, p, o, m) ROOST_PP_FOR_29_I(s, p, o, m)
# define ROOST_PP_FOR_30(s, p, o, m) ROOST_PP_FOR_30_I(s, p, o, m)
# define ROOST_PP_FOR_31(s, p, o, m) ROOST_PP_FOR_31_I(s, p, o, m)
# define ROOST_PP_FOR_32(s, p, o, m) ROOST_PP_FOR_32_I(s, p, o, m)
# define ROOST_PP_FOR_33(s, p, o, m) ROOST_PP_FOR_33_I(s, p, o, m)
# define ROOST_PP_FOR_34(s, p, o, m) ROOST_PP_FOR_34_I(s, p, o, m)
# define ROOST_PP_FOR_35(s, p, o, m) ROOST_PP_FOR_35_I(s, p, o, m)
# define ROOST_PP_FOR_36(s, p, o, m) ROOST_PP_FOR_36_I(s, p, o, m)
# define ROOST_PP_FOR_37(s, p, o, m) ROOST_PP_FOR_37_I(s, p, o, m)
# define ROOST_PP_FOR_38(s, p, o, m) ROOST_PP_FOR_38_I(s, p, o, m)
# define ROOST_PP_FOR_39(s, p, o, m) ROOST_PP_FOR_39_I(s, p, o, m)
# define ROOST_PP_FOR_40(s, p, o, m) ROOST_PP_FOR_40_I(s, p, o, m)
# define ROOST_PP_FOR_41(s, p, o, m) ROOST_PP_FOR_41_I(s, p, o, m)
# define ROOST_PP_FOR_42(s, p, o, m) ROOST_PP_FOR_42_I(s, p, o, m)
# define ROOST_PP_FOR_43(s, p, o, m) ROOST_PP_FOR_43_I(s, p, o, m)
# define ROOST_PP_FOR_44(s, p, o, m) ROOST_PP_FOR_44_I(s, p, o, m)
# define ROOST_PP_FOR_45(s, p, o, m) ROOST_PP_FOR_45_I(s, p, o, m)
# define ROOST_PP_FOR_46(s, p, o, m) ROOST_PP_FOR_46_I(s, p, o, m)
# define ROOST_PP_FOR_47(s, p, o, m) ROOST_PP_FOR_47_I(s, p, o, m)
# define ROOST_PP_FOR_48(s, p, o, m) ROOST_PP_FOR_48_I(s, p, o, m)
# define ROOST_PP_FOR_49(s, p, o, m) ROOST_PP_FOR_49_I(s, p, o, m)
# define ROOST_PP_FOR_50(s, p, o, m) ROOST_PP_FOR_50_I(s, p, o, m)
# define ROOST_PP_FOR_51(s, p, o, m) ROOST_PP_FOR_51_I(s, p, o, m)
# define ROOST_PP_FOR_52(s, p, o, m) ROOST_PP_FOR_52_I(s, p, o, m)
# define ROOST_PP_FOR_53(s, p, o, m) ROOST_PP_FOR_53_I(s, p, o, m)
# define ROOST_PP_FOR_54(s, p, o, m) ROOST_PP_FOR_54_I(s, p, o, m)
# define ROOST_PP_FOR_55(s, p, o, m) ROOST_PP_FOR_55_I(s, p, o, m)
# define ROOST_PP_FOR_56(s, p, o, m) ROOST_PP_FOR_56_I(s, p, o, m)
# define ROOST_PP_FOR_57(s, p, o, m) ROOST_PP_FOR_57_I(s, p, o, m)
# define ROOST_PP_FOR_58(s, p, o, m) ROOST_PP_FOR_58_I(s, p, o, m)
# define ROOST_PP_FOR_59(s, p, o, m) ROOST_PP_FOR_59_I(s, p, o, m)
# define ROOST_PP_FOR_60(s, p, o, m) ROOST_PP_FOR_60_I(s, p, o, m)
# define ROOST_PP_FOR_61(s, p, o, m) ROOST_PP_FOR_61_I(s, p, o, m)
# define ROOST_PP_FOR_62(s, p, o, m) ROOST_PP_FOR_62_I(s, p, o, m)
# define ROOST_PP_FOR_63(s, p, o, m) ROOST_PP_FOR_63_I(s, p, o, m)
# define ROOST_PP_FOR_64(s, p, o, m) ROOST_PP_FOR_64_I(s, p, o, m)
# define ROOST_PP_FOR_65(s, p, o, m) ROOST_PP_FOR_65_I(s, p, o, m)
# define ROOST_PP_FOR_66(s, p, o, m) ROOST_PP_FOR_66_I(s, p, o, m)
# define ROOST_PP_FOR_67(s, p, o, m) ROOST_PP_FOR_67_I(s, p, o, m)
# define ROOST_PP_FOR_68(s, p, o, m) ROOST_PP_FOR_68_I(s, p, o, m)
# define ROOST_PP_FOR_69(s, p, o, m) ROOST_PP_FOR_69_I(s, p, o, m)
# define ROOST_PP_FOR_70(s, p, o, m) ROOST_PP_FOR_70_I(s, p, o, m)
# define ROOST_PP_FOR_71(s, p, o, m) ROOST_PP_FOR_71_I(s, p, o, m)
# define ROOST_PP_FOR_72(s, p, o, m) ROOST_PP_FOR_72_I(s, p, o, m)
# define ROOST_PP_FOR_73(s, p, o, m) ROOST_PP_FOR_73_I(s, p, o, m)
# define ROOST_PP_FOR_74(s, p, o, m) ROOST_PP_FOR_74_I(s, p, o, m)
# define ROOST_PP_FOR_75(s, p, o, m) ROOST_PP_FOR_75_I(s, p, o, m)
# define ROOST_PP_FOR_76(s, p, o, m) ROOST_PP_FOR_76_I(s, p, o, m)
# define ROOST_PP_FOR_77(s, p, o, m) ROOST_PP_FOR_77_I(s, p, o, m)
# define ROOST_PP_FOR_78(s, p, o, m) ROOST_PP_FOR_78_I(s, p, o, m)
# define ROOST_PP_FOR_79(s, p, o, m) ROOST_PP_FOR_79_I(s, p, o, m)
# define ROOST_PP_FOR_80(s, p, o, m) ROOST_PP_FOR_80_I(s, p, o, m)
# define ROOST_PP_FOR_81(s, p, o, m) ROOST_PP_FOR_81_I(s, p, o, m)
# define ROOST_PP_FOR_82(s, p, o, m) ROOST_PP_FOR_82_I(s, p, o, m)
# define ROOST_PP_FOR_83(s, p, o, m) ROOST_PP_FOR_83_I(s, p, o, m)
# define ROOST_PP_FOR_84(s, p, o, m) ROOST_PP_FOR_84_I(s, p, o, m)
# define ROOST_PP_FOR_85(s, p, o, m) ROOST_PP_FOR_85_I(s, p, o, m)
# define ROOST_PP_FOR_86(s, p, o, m) ROOST_PP_FOR_86_I(s, p, o, m)
# define ROOST_PP_FOR_87(s, p, o, m) ROOST_PP_FOR_87_I(s, p, o, m)
# define ROOST_PP_FOR_88(s, p, o, m) ROOST_PP_FOR_88_I(s, p, o, m)
# define ROOST_PP_FOR_89(s, p, o, m) ROOST_PP_FOR_89_I(s, p, o, m)
# define ROOST_PP_FOR_90(s, p, o, m) ROOST_PP_FOR_90_I(s, p, o, m)
# define ROOST_PP_FOR_91(s, p, o, m) ROOST_PP_FOR_91_I(s, p, o, m)
# define ROOST_PP_FOR_92(s, p, o, m) ROOST_PP_FOR_92_I(s, p, o, m)
# define ROOST_PP_FOR_93(s, p, o, m) ROOST_PP_FOR_93_I(s, p, o, m)
# define ROOST_PP_FOR_94(s, p, o, m) ROOST_PP_FOR_94_I(s, p, o, m)
# define ROOST_PP_FOR_95(s, p, o, m) ROOST_PP_FOR_95_I(s, p, o, m)
# define ROOST_PP_FOR_96(s, p, o, m) ROOST_PP_FOR_96_I(s, p, o, m)
# define ROOST_PP_FOR_97(s, p, o, m) ROOST_PP_FOR_97_I(s, p, o, m)
# define ROOST_PP_FOR_98(s, p, o, m) ROOST_PP_FOR_98_I(s, p, o, m)
# define ROOST_PP_FOR_99(s, p, o, m) ROOST_PP_FOR_99_I(s, p, o, m)
# define ROOST_PP_FOR_100(s, p, o, m) ROOST_PP_FOR_100_I(s, p, o, m)
# define ROOST_PP_FOR_101(s, p, o, m) ROOST_PP_FOR_101_I(s, p, o, m)
# define ROOST_PP_FOR_102(s, p, o, m) ROOST_PP_FOR_102_I(s, p, o, m)
# define ROOST_PP_FOR_103(s, p, o, m) ROOST_PP_FOR_103_I(s, p, o, m)
# define ROOST_PP_FOR_104(s, p, o, m) ROOST_PP_FOR_104_I(s, p, o, m)
# define ROOST_PP_FOR_105(s, p, o, m) ROOST_PP_FOR_105_I(s, p, o, m)
# define ROOST_PP_FOR_106(s, p, o, m) ROOST_PP_FOR_106_I(s, p, o, m)
# define ROOST_PP_FOR_107(s, p, o, m) ROOST_PP_FOR_107_I(s, p, o, m)
# define ROOST_PP_FOR_108(s, p, o, m) ROOST_PP_FOR_108_I(s, p, o, m)
# define ROOST_PP_FOR_109(s, p, o, m) ROOST_PP_FOR_109_I(s, p, o, m)
# define ROOST_PP_FOR_110(s, p, o, m) ROOST_PP_FOR_110_I(s, p, o, m)
# define ROOST_PP_FOR_111(s, p, o, m) ROOST_PP_FOR_111_I(s, p, o, m)
# define ROOST_PP_FOR_112(s, p, o, m) ROOST_PP_FOR_112_I(s, p, o, m)
# define ROOST_PP_FOR_113(s, p, o, m) ROOST_PP_FOR_113_I(s, p, o, m)
# define ROOST_PP_FOR_114(s, p, o, m) ROOST_PP_FOR_114_I(s, p, o, m)
# define ROOST_PP_FOR_115(s, p, o, m) ROOST_PP_FOR_115_I(s, p, o, m)
# define ROOST_PP_FOR_116(s, p, o, m) ROOST_PP_FOR_116_I(s, p, o, m)
# define ROOST_PP_FOR_117(s, p, o, m) ROOST_PP_FOR_117_I(s, p, o, m)
# define ROOST_PP_FOR_118(s, p, o, m) ROOST_PP_FOR_118_I(s, p, o, m)
# define ROOST_PP_FOR_119(s, p, o, m) ROOST_PP_FOR_119_I(s, p, o, m)
# define ROOST_PP_FOR_120(s, p, o, m) ROOST_PP_FOR_120_I(s, p, o, m)
# define ROOST_PP_FOR_121(s, p, o, m) ROOST_PP_FOR_121_I(s, p, o, m)
# define ROOST_PP_FOR_122(s, p, o, m) ROOST_PP_FOR_122_I(s, p, o, m)
# define ROOST_PP_FOR_123(s, p, o, m) ROOST_PP_FOR_123_I(s, p, o, m)
# define ROOST_PP_FOR_124(s, p, o, m) ROOST_PP_FOR_124_I(s, p, o, m)
# define ROOST_PP_FOR_125(s, p, o, m) ROOST_PP_FOR_125_I(s, p, o, m)
# define ROOST_PP_FOR_126(s, p, o, m) ROOST_PP_FOR_126_I(s, p, o, m)
# define ROOST_PP_FOR_127(s, p, o, m) ROOST_PP_FOR_127_I(s, p, o, m)
# define ROOST_PP_FOR_128(s, p, o, m) ROOST_PP_FOR_128_I(s, p, o, m)
# define ROOST_PP_FOR_129(s, p, o, m) ROOST_PP_FOR_129_I(s, p, o, m)
# define ROOST_PP_FOR_130(s, p, o, m) ROOST_PP_FOR_130_I(s, p, o, m)
# define ROOST_PP_FOR_131(s, p, o, m) ROOST_PP_FOR_131_I(s, p, o, m)
# define ROOST_PP_FOR_132(s, p, o, m) ROOST_PP_FOR_132_I(s, p, o, m)
# define ROOST_PP_FOR_133(s, p, o, m) ROOST_PP_FOR_133_I(s, p, o, m)
# define ROOST_PP_FOR_134(s, p, o, m) ROOST_PP_FOR_134_I(s, p, o, m)
# define ROOST_PP_FOR_135(s, p, o, m) ROOST_PP_FOR_135_I(s, p, o, m)
# define ROOST_PP_FOR_136(s, p, o, m) ROOST_PP_FOR_136_I(s, p, o, m)
# define ROOST_PP_FOR_137(s, p, o, m) ROOST_PP_FOR_137_I(s, p, o, m)
# define ROOST_PP_FOR_138(s, p, o, m) ROOST_PP_FOR_138_I(s, p, o, m)
# define ROOST_PP_FOR_139(s, p, o, m) ROOST_PP_FOR_139_I(s, p, o, m)
# define ROOST_PP_FOR_140(s, p, o, m) ROOST_PP_FOR_140_I(s, p, o, m)
# define ROOST_PP_FOR_141(s, p, o, m) ROOST_PP_FOR_141_I(s, p, o, m)
# define ROOST_PP_FOR_142(s, p, o, m) ROOST_PP_FOR_142_I(s, p, o, m)
# define ROOST_PP_FOR_143(s, p, o, m) ROOST_PP_FOR_143_I(s, p, o, m)
# define ROOST_PP_FOR_144(s, p, o, m) ROOST_PP_FOR_144_I(s, p, o, m)
# define ROOST_PP_FOR_145(s, p, o, m) ROOST_PP_FOR_145_I(s, p, o, m)
# define ROOST_PP_FOR_146(s, p, o, m) ROOST_PP_FOR_146_I(s, p, o, m)
# define ROOST_PP_FOR_147(s, p, o, m) ROOST_PP_FOR_147_I(s, p, o, m)
# define ROOST_PP_FOR_148(s, p, o, m) ROOST_PP_FOR_148_I(s, p, o, m)
# define ROOST_PP_FOR_149(s, p, o, m) ROOST_PP_FOR_149_I(s, p, o, m)
# define ROOST_PP_FOR_150(s, p, o, m) ROOST_PP_FOR_150_I(s, p, o, m)
# define ROOST_PP_FOR_151(s, p, o, m) ROOST_PP_FOR_151_I(s, p, o, m)
# define ROOST_PP_FOR_152(s, p, o, m) ROOST_PP_FOR_152_I(s, p, o, m)
# define ROOST_PP_FOR_153(s, p, o, m) ROOST_PP_FOR_153_I(s, p, o, m)
# define ROOST_PP_FOR_154(s, p, o, m) ROOST_PP_FOR_154_I(s, p, o, m)
# define ROOST_PP_FOR_155(s, p, o, m) ROOST_PP_FOR_155_I(s, p, o, m)
# define ROOST_PP_FOR_156(s, p, o, m) ROOST_PP_FOR_156_I(s, p, o, m)
# define ROOST_PP_FOR_157(s, p, o, m) ROOST_PP_FOR_157_I(s, p, o, m)
# define ROOST_PP_FOR_158(s, p, o, m) ROOST_PP_FOR_158_I(s, p, o, m)
# define ROOST_PP_FOR_159(s, p, o, m) ROOST_PP_FOR_159_I(s, p, o, m)
# define ROOST_PP_FOR_160(s, p, o, m) ROOST_PP_FOR_160_I(s, p, o, m)
# define ROOST_PP_FOR_161(s, p, o, m) ROOST_PP_FOR_161_I(s, p, o, m)
# define ROOST_PP_FOR_162(s, p, o, m) ROOST_PP_FOR_162_I(s, p, o, m)
# define ROOST_PP_FOR_163(s, p, o, m) ROOST_PP_FOR_163_I(s, p, o, m)
# define ROOST_PP_FOR_164(s, p, o, m) ROOST_PP_FOR_164_I(s, p, o, m)
# define ROOST_PP_FOR_165(s, p, o, m) ROOST_PP_FOR_165_I(s, p, o, m)
# define ROOST_PP_FOR_166(s, p, o, m) ROOST_PP_FOR_166_I(s, p, o, m)
# define ROOST_PP_FOR_167(s, p, o, m) ROOST_PP_FOR_167_I(s, p, o, m)
# define ROOST_PP_FOR_168(s, p, o, m) ROOST_PP_FOR_168_I(s, p, o, m)
# define ROOST_PP_FOR_169(s, p, o, m) ROOST_PP_FOR_169_I(s, p, o, m)
# define ROOST_PP_FOR_170(s, p, o, m) ROOST_PP_FOR_170_I(s, p, o, m)
# define ROOST_PP_FOR_171(s, p, o, m) ROOST_PP_FOR_171_I(s, p, o, m)
# define ROOST_PP_FOR_172(s, p, o, m) ROOST_PP_FOR_172_I(s, p, o, m)
# define ROOST_PP_FOR_173(s, p, o, m) ROOST_PP_FOR_173_I(s, p, o, m)
# define ROOST_PP_FOR_174(s, p, o, m) ROOST_PP_FOR_174_I(s, p, o, m)
# define ROOST_PP_FOR_175(s, p, o, m) ROOST_PP_FOR_175_I(s, p, o, m)
# define ROOST_PP_FOR_176(s, p, o, m) ROOST_PP_FOR_176_I(s, p, o, m)
# define ROOST_PP_FOR_177(s, p, o, m) ROOST_PP_FOR_177_I(s, p, o, m)
# define ROOST_PP_FOR_178(s, p, o, m) ROOST_PP_FOR_178_I(s, p, o, m)
# define ROOST_PP_FOR_179(s, p, o, m) ROOST_PP_FOR_179_I(s, p, o, m)
# define ROOST_PP_FOR_180(s, p, o, m) ROOST_PP_FOR_180_I(s, p, o, m)
# define ROOST_PP_FOR_181(s, p, o, m) ROOST_PP_FOR_181_I(s, p, o, m)
# define ROOST_PP_FOR_182(s, p, o, m) ROOST_PP_FOR_182_I(s, p, o, m)
# define ROOST_PP_FOR_183(s, p, o, m) ROOST_PP_FOR_183_I(s, p, o, m)
# define ROOST_PP_FOR_184(s, p, o, m) ROOST_PP_FOR_184_I(s, p, o, m)
# define ROOST_PP_FOR_185(s, p, o, m) ROOST_PP_FOR_185_I(s, p, o, m)
# define ROOST_PP_FOR_186(s, p, o, m) ROOST_PP_FOR_186_I(s, p, o, m)
# define ROOST_PP_FOR_187(s, p, o, m) ROOST_PP_FOR_187_I(s, p, o, m)
# define ROOST_PP_FOR_188(s, p, o, m) ROOST_PP_FOR_188_I(s, p, o, m)
# define ROOST_PP_FOR_189(s, p, o, m) ROOST_PP_FOR_189_I(s, p, o, m)
# define ROOST_PP_FOR_190(s, p, o, m) ROOST_PP_FOR_190_I(s, p, o, m)
# define ROOST_PP_FOR_191(s, p, o, m) ROOST_PP_FOR_191_I(s, p, o, m)
# define ROOST_PP_FOR_192(s, p, o, m) ROOST_PP_FOR_192_I(s, p, o, m)
# define ROOST_PP_FOR_193(s, p, o, m) ROOST_PP_FOR_193_I(s, p, o, m)
# define ROOST_PP_FOR_194(s, p, o, m) ROOST_PP_FOR_194_I(s, p, o, m)
# define ROOST_PP_FOR_195(s, p, o, m) ROOST_PP_FOR_195_I(s, p, o, m)
# define ROOST_PP_FOR_196(s, p, o, m) ROOST_PP_FOR_196_I(s, p, o, m)
# define ROOST_PP_FOR_197(s, p, o, m) ROOST_PP_FOR_197_I(s, p, o, m)
# define ROOST_PP_FOR_198(s, p, o, m) ROOST_PP_FOR_198_I(s, p, o, m)
# define ROOST_PP_FOR_199(s, p, o, m) ROOST_PP_FOR_199_I(s, p, o, m)
# define ROOST_PP_FOR_200(s, p, o, m) ROOST_PP_FOR_200_I(s, p, o, m)
# define ROOST_PP_FOR_201(s, p, o, m) ROOST_PP_FOR_201_I(s, p, o, m)
# define ROOST_PP_FOR_202(s, p, o, m) ROOST_PP_FOR_202_I(s, p, o, m)
# define ROOST_PP_FOR_203(s, p, o, m) ROOST_PP_FOR_203_I(s, p, o, m)
# define ROOST_PP_FOR_204(s, p, o, m) ROOST_PP_FOR_204_I(s, p, o, m)
# define ROOST_PP_FOR_205(s, p, o, m) ROOST_PP_FOR_205_I(s, p, o, m)
# define ROOST_PP_FOR_206(s, p, o, m) ROOST_PP_FOR_206_I(s, p, o, m)
# define ROOST_PP_FOR_207(s, p, o, m) ROOST_PP_FOR_207_I(s, p, o, m)
# define ROOST_PP_FOR_208(s, p, o, m) ROOST_PP_FOR_208_I(s, p, o, m)
# define ROOST_PP_FOR_209(s, p, o, m) ROOST_PP_FOR_209_I(s, p, o, m)
# define ROOST_PP_FOR_210(s, p, o, m) ROOST_PP_FOR_210_I(s, p, o, m)
# define ROOST_PP_FOR_211(s, p, o, m) ROOST_PP_FOR_211_I(s, p, o, m)
# define ROOST_PP_FOR_212(s, p, o, m) ROOST_PP_FOR_212_I(s, p, o, m)
# define ROOST_PP_FOR_213(s, p, o, m) ROOST_PP_FOR_213_I(s, p, o, m)
# define ROOST_PP_FOR_214(s, p, o, m) ROOST_PP_FOR_214_I(s, p, o, m)
# define ROOST_PP_FOR_215(s, p, o, m) ROOST_PP_FOR_215_I(s, p, o, m)
# define ROOST_PP_FOR_216(s, p, o, m) ROOST_PP_FOR_216_I(s, p, o, m)
# define ROOST_PP_FOR_217(s, p, o, m) ROOST_PP_FOR_217_I(s, p, o, m)
# define ROOST_PP_FOR_218(s, p, o, m) ROOST_PP_FOR_218_I(s, p, o, m)
# define ROOST_PP_FOR_219(s, p, o, m) ROOST_PP_FOR_219_I(s, p, o, m)
# define ROOST_PP_FOR_220(s, p, o, m) ROOST_PP_FOR_220_I(s, p, o, m)
# define ROOST_PP_FOR_221(s, p, o, m) ROOST_PP_FOR_221_I(s, p, o, m)
# define ROOST_PP_FOR_222(s, p, o, m) ROOST_PP_FOR_222_I(s, p, o, m)
# define ROOST_PP_FOR_223(s, p, o, m) ROOST_PP_FOR_223_I(s, p, o, m)
# define ROOST_PP_FOR_224(s, p, o, m) ROOST_PP_FOR_224_I(s, p, o, m)
# define ROOST_PP_FOR_225(s, p, o, m) ROOST_PP_FOR_225_I(s, p, o, m)
# define ROOST_PP_FOR_226(s, p, o, m) ROOST_PP_FOR_226_I(s, p, o, m)
# define ROOST_PP_FOR_227(s, p, o, m) ROOST_PP_FOR_227_I(s, p, o, m)
# define ROOST_PP_FOR_228(s, p, o, m) ROOST_PP_FOR_228_I(s, p, o, m)
# define ROOST_PP_FOR_229(s, p, o, m) ROOST_PP_FOR_229_I(s, p, o, m)
# define ROOST_PP_FOR_230(s, p, o, m) ROOST_PP_FOR_230_I(s, p, o, m)
# define ROOST_PP_FOR_231(s, p, o, m) ROOST_PP_FOR_231_I(s, p, o, m)
# define ROOST_PP_FOR_232(s, p, o, m) ROOST_PP_FOR_232_I(s, p, o, m)
# define ROOST_PP_FOR_233(s, p, o, m) ROOST_PP_FOR_233_I(s, p, o, m)
# define ROOST_PP_FOR_234(s, p, o, m) ROOST_PP_FOR_234_I(s, p, o, m)
# define ROOST_PP_FOR_235(s, p, o, m) ROOST_PP_FOR_235_I(s, p, o, m)
# define ROOST_PP_FOR_236(s, p, o, m) ROOST_PP_FOR_236_I(s, p, o, m)
# define ROOST_PP_FOR_237(s, p, o, m) ROOST_PP_FOR_237_I(s, p, o, m)
# define ROOST_PP_FOR_238(s, p, o, m) ROOST_PP_FOR_238_I(s, p, o, m)
# define ROOST_PP_FOR_239(s, p, o, m) ROOST_PP_FOR_239_I(s, p, o, m)
# define ROOST_PP_FOR_240(s, p, o, m) ROOST_PP_FOR_240_I(s, p, o, m)
# define ROOST_PP_FOR_241(s, p, o, m) ROOST_PP_FOR_241_I(s, p, o, m)
# define ROOST_PP_FOR_242(s, p, o, m) ROOST_PP_FOR_242_I(s, p, o, m)
# define ROOST_PP_FOR_243(s, p, o, m) ROOST_PP_FOR_243_I(s, p, o, m)
# define ROOST_PP_FOR_244(s, p, o, m) ROOST_PP_FOR_244_I(s, p, o, m)
# define ROOST_PP_FOR_245(s, p, o, m) ROOST_PP_FOR_245_I(s, p, o, m)
# define ROOST_PP_FOR_246(s, p, o, m) ROOST_PP_FOR_246_I(s, p, o, m)
# define ROOST_PP_FOR_247(s, p, o, m) ROOST_PP_FOR_247_I(s, p, o, m)
# define ROOST_PP_FOR_248(s, p, o, m) ROOST_PP_FOR_248_I(s, p, o, m)
# define ROOST_PP_FOR_249(s, p, o, m) ROOST_PP_FOR_249_I(s, p, o, m)
# define ROOST_PP_FOR_250(s, p, o, m) ROOST_PP_FOR_250_I(s, p, o, m)
# define ROOST_PP_FOR_251(s, p, o, m) ROOST_PP_FOR_251_I(s, p, o, m)
# define ROOST_PP_FOR_252(s, p, o, m) ROOST_PP_FOR_252_I(s, p, o, m)
# define ROOST_PP_FOR_253(s, p, o, m) ROOST_PP_FOR_253_I(s, p, o, m)
# define ROOST_PP_FOR_254(s, p, o, m) ROOST_PP_FOR_254_I(s, p, o, m)
# define ROOST_PP_FOR_255(s, p, o, m) ROOST_PP_FOR_255_I(s, p, o, m)
# define ROOST_PP_FOR_256(s, p, o, m) ROOST_PP_FOR_256_I(s, p, o, m)
#
# define ROOST_PP_FOR_1_I(s, p, o, m) ROOST_PP_IF(p(2, s), m, ROOST_PP_TUPLE_EAT_2)(2, s) ROOST_PP_IF(p(2, s), ROOST_PP_FOR_2, ROOST_PP_TUPLE_EAT_4)(o(2, s), p, o, m)
# define ROOST_PP_FOR_2_I(s, p, o, m) ROOST_PP_IF(p(3, s), m, ROOST_PP_TUPLE_EAT_2)(3, s) ROOST_PP_IF(p(3, s), ROOST_PP_FOR_3, ROOST_PP_TUPLE_EAT_4)(o(3, s), p, o, m)
# define ROOST_PP_FOR_3_I(s, p, o, m) ROOST_PP_IF(p(4, s), m, ROOST_PP_TUPLE_EAT_2)(4, s) ROOST_PP_IF(p(4, s), ROOST_PP_FOR_4, ROOST_PP_TUPLE_EAT_4)(o(4, s), p, o, m)
# define ROOST_PP_FOR_4_I(s, p, o, m) ROOST_PP_IF(p(5, s), m, ROOST_PP_TUPLE_EAT_2)(5, s) ROOST_PP_IF(p(5, s), ROOST_PP_FOR_5, ROOST_PP_TUPLE_EAT_4)(o(5, s), p, o, m)
# define ROOST_PP_FOR_5_I(s, p, o, m) ROOST_PP_IF(p(6, s), m, ROOST_PP_TUPLE_EAT_2)(6, s) ROOST_PP_IF(p(6, s), ROOST_PP_FOR_6, ROOST_PP_TUPLE_EAT_4)(o(6, s), p, o, m)
# define ROOST_PP_FOR_6_I(s, p, o, m) ROOST_PP_IF(p(7, s), m, ROOST_PP_TUPLE_EAT_2)(7, s) ROOST_PP_IF(p(7, s), ROOST_PP_FOR_7, ROOST_PP_TUPLE_EAT_4)(o(7, s), p, o, m)
# define ROOST_PP_FOR_7_I(s, p, o, m) ROOST_PP_IF(p(8, s), m, ROOST_PP_TUPLE_EAT_2)(8, s) ROOST_PP_IF(p(8, s), ROOST_PP_FOR_8, ROOST_PP_TUPLE_EAT_4)(o(8, s), p, o, m)
# define ROOST_PP_FOR_8_I(s, p, o, m) ROOST_PP_IF(p(9, s), m, ROOST_PP_TUPLE_EAT_2)(9, s) ROOST_PP_IF(p(9, s), ROOST_PP_FOR_9, ROOST_PP_TUPLE_EAT_4)(o(9, s), p, o, m)
# define ROOST_PP_FOR_9_I(s, p, o, m) ROOST_PP_IF(p(10, s), m, ROOST_PP_TUPLE_EAT_2)(10, s) ROOST_PP_IF(p(10, s), ROOST_PP_FOR_10, ROOST_PP_TUPLE_EAT_4)(o(10, s), p, o, m)
# define ROOST_PP_FOR_10_I(s, p, o, m) ROOST_PP_IF(p(11, s), m, ROOST_PP_TUPLE_EAT_2)(11, s) ROOST_PP_IF(p(11, s), ROOST_PP_FOR_11, ROOST_PP_TUPLE_EAT_4)(o(11, s), p, o, m)
# define ROOST_PP_FOR_11_I(s, p, o, m) ROOST_PP_IF(p(12, s), m, ROOST_PP_TUPLE_EAT_2)(12, s) ROOST_PP_IF(p(12, s), ROOST_PP_FOR_12, ROOST_PP_TUPLE_EAT_4)(o(12, s), p, o, m)
# define ROOST_PP_FOR_12_I(s, p, o, m) ROOST_PP_IF(p(13, s), m, ROOST_PP_TUPLE_EAT_2)(13, s) ROOST_PP_IF(p(13, s), ROOST_PP_FOR_13, ROOST_PP_TUPLE_EAT_4)(o(13, s), p, o, m)
# define ROOST_PP_FOR_13_I(s, p, o, m) ROOST_PP_IF(p(14, s), m, ROOST_PP_TUPLE_EAT_2)(14, s) ROOST_PP_IF(p(14, s), ROOST_PP_FOR_14, ROOST_PP_TUPLE_EAT_4)(o(14, s), p, o, m)
# define ROOST_PP_FOR_14_I(s, p, o, m) ROOST_PP_IF(p(15, s), m, ROOST_PP_TUPLE_EAT_2)(15, s) ROOST_PP_IF(p(15, s), ROOST_PP_FOR_15, ROOST_PP_TUPLE_EAT_4)(o(15, s), p, o, m)
# define ROOST_PP_FOR_15_I(s, p, o, m) ROOST_PP_IF(p(16, s), m, ROOST_PP_TUPLE_EAT_2)(16, s) ROOST_PP_IF(p(16, s), ROOST_PP_FOR_16, ROOST_PP_TUPLE_EAT_4)(o(16, s), p, o, m)
# define ROOST_PP_FOR_16_I(s, p, o, m) ROOST_PP_IF(p(17, s), m, ROOST_PP_TUPLE_EAT_2)(17, s) ROOST_PP_IF(p(17, s), ROOST_PP_FOR_17, ROOST_PP_TUPLE_EAT_4)(o(17, s), p, o, m)
# define ROOST_PP_FOR_17_I(s, p, o, m) ROOST_PP_IF(p(18, s), m, ROOST_PP_TUPLE_EAT_2)(18, s) ROOST_PP_IF(p(18, s), ROOST_PP_FOR_18, ROOST_PP_TUPLE_EAT_4)(o(18, s), p, o, m)
# define ROOST_PP_FOR_18_I(s, p, o, m) ROOST_PP_IF(p(19, s), m, ROOST_PP_TUPLE_EAT_2)(19, s) ROOST_PP_IF(p(19, s), ROOST_PP_FOR_19, ROOST_PP_TUPLE_EAT_4)(o(19, s), p, o, m)
# define ROOST_PP_FOR_19_I(s, p, o, m) ROOST_PP_IF(p(20, s), m, ROOST_PP_TUPLE_EAT_2)(20, s) ROOST_PP_IF(p(20, s), ROOST_PP_FOR_20, ROOST_PP_TUPLE_EAT_4)(o(20, s), p, o, m)
# define ROOST_PP_FOR_20_I(s, p, o, m) ROOST_PP_IF(p(21, s), m, ROOST_PP_TUPLE_EAT_2)(21, s) ROOST_PP_IF(p(21, s), ROOST_PP_FOR_21, ROOST_PP_TUPLE_EAT_4)(o(21, s), p, o, m)
# define ROOST_PP_FOR_21_I(s, p, o, m) ROOST_PP_IF(p(22, s), m, ROOST_PP_TUPLE_EAT_2)(22, s) ROOST_PP_IF(p(22, s), ROOST_PP_FOR_22, ROOST_PP_TUPLE_EAT_4)(o(22, s), p, o, m)
# define ROOST_PP_FOR_22_I(s, p, o, m) ROOST_PP_IF(p(23, s), m, ROOST_PP_TUPLE_EAT_2)(23, s) ROOST_PP_IF(p(23, s), ROOST_PP_FOR_23, ROOST_PP_TUPLE_EAT_4)(o(23, s), p, o, m)
# define ROOST_PP_FOR_23_I(s, p, o, m) ROOST_PP_IF(p(24, s), m, ROOST_PP_TUPLE_EAT_2)(24, s) ROOST_PP_IF(p(24, s), ROOST_PP_FOR_24, ROOST_PP_TUPLE_EAT_4)(o(24, s), p, o, m)
# define ROOST_PP_FOR_24_I(s, p, o, m) ROOST_PP_IF(p(25, s), m, ROOST_PP_TUPLE_EAT_2)(25, s) ROOST_PP_IF(p(25, s), ROOST_PP_FOR_25, ROOST_PP_TUPLE_EAT_4)(o(25, s), p, o, m)
# define ROOST_PP_FOR_25_I(s, p, o, m) ROOST_PP_IF(p(26, s), m, ROOST_PP_TUPLE_EAT_2)(26, s) ROOST_PP_IF(p(26, s), ROOST_PP_FOR_26, ROOST_PP_TUPLE_EAT_4)(o(26, s), p, o, m)
# define ROOST_PP_FOR_26_I(s, p, o, m) ROOST_PP_IF(p(27, s), m, ROOST_PP_TUPLE_EAT_2)(27, s) ROOST_PP_IF(p(27, s), ROOST_PP_FOR_27, ROOST_PP_TUPLE_EAT_4)(o(27, s), p, o, m)
# define ROOST_PP_FOR_27_I(s, p, o, m) ROOST_PP_IF(p(28, s), m, ROOST_PP_TUPLE_EAT_2)(28, s) ROOST_PP_IF(p(28, s), ROOST_PP_FOR_28, ROOST_PP_TUPLE_EAT_4)(o(28, s), p, o, m)
# define ROOST_PP_FOR_28_I(s, p, o, m) ROOST_PP_IF(p(29, s), m, ROOST_PP_TUPLE_EAT_2)(29, s) ROOST_PP_IF(p(29, s), ROOST_PP_FOR_29, ROOST_PP_TUPLE_EAT_4)(o(29, s), p, o, m)
# define ROOST_PP_FOR_29_I(s, p, o, m) ROOST_PP_IF(p(30, s), m, ROOST_PP_TUPLE_EAT_2)(30, s) ROOST_PP_IF(p(30, s), ROOST_PP_FOR_30, ROOST_PP_TUPLE_EAT_4)(o(30, s), p, o, m)
# define ROOST_PP_FOR_30_I(s, p, o, m) ROOST_PP_IF(p(31, s), m, ROOST_PP_TUPLE_EAT_2)(31, s) ROOST_PP_IF(p(31, s), ROOST_PP_FOR_31, ROOST_PP_TUPLE_EAT_4)(o(31, s), p, o, m)
# define ROOST_PP_FOR_31_I(s, p, o, m) ROOST_PP_IF(p(32, s), m, ROOST_PP_TUPLE_EAT_2)(32, s) ROOST_PP_IF(p(32, s), ROOST_PP_FOR_32, ROOST_PP_TUPLE_EAT_4)(o(32, s), p, o, m)
# define ROOST_PP_FOR_32_I(s, p, o, m) ROOST_PP_IF(p(33, s), m, ROOST_PP_TUPLE_EAT_2)(33, s) ROOST_PP_IF(p(33, s), ROOST_PP_FOR_33, ROOST_PP_TUPLE_EAT_4)(o(33, s), p, o, m)
# define ROOST_PP_FOR_33_I(s, p, o, m) ROOST_PP_IF(p(34, s), m, ROOST_PP_TUPLE_EAT_2)(34, s) ROOST_PP_IF(p(34, s), ROOST_PP_FOR_34, ROOST_PP_TUPLE_EAT_4)(o(34, s), p, o, m)
# define ROOST_PP_FOR_34_I(s, p, o, m) ROOST_PP_IF(p(35, s), m, ROOST_PP_TUPLE_EAT_2)(35, s) ROOST_PP_IF(p(35, s), ROOST_PP_FOR_35, ROOST_PP_TUPLE_EAT_4)(o(35, s), p, o, m)
# define ROOST_PP_FOR_35_I(s, p, o, m) ROOST_PP_IF(p(36, s), m, ROOST_PP_TUPLE_EAT_2)(36, s) ROOST_PP_IF(p(36, s), ROOST_PP_FOR_36, ROOST_PP_TUPLE_EAT_4)(o(36, s), p, o, m)
# define ROOST_PP_FOR_36_I(s, p, o, m) ROOST_PP_IF(p(37, s), m, ROOST_PP_TUPLE_EAT_2)(37, s) ROOST_PP_IF(p(37, s), ROOST_PP_FOR_37, ROOST_PP_TUPLE_EAT_4)(o(37, s), p, o, m)
# define ROOST_PP_FOR_37_I(s, p, o, m) ROOST_PP_IF(p(38, s), m, ROOST_PP_TUPLE_EAT_2)(38, s) ROOST_PP_IF(p(38, s), ROOST_PP_FOR_38, ROOST_PP_TUPLE_EAT_4)(o(38, s), p, o, m)
# define ROOST_PP_FOR_38_I(s, p, o, m) ROOST_PP_IF(p(39, s), m, ROOST_PP_TUPLE_EAT_2)(39, s) ROOST_PP_IF(p(39, s), ROOST_PP_FOR_39, ROOST_PP_TUPLE_EAT_4)(o(39, s), p, o, m)
# define ROOST_PP_FOR_39_I(s, p, o, m) ROOST_PP_IF(p(40, s), m, ROOST_PP_TUPLE_EAT_2)(40, s) ROOST_PP_IF(p(40, s), ROOST_PP_FOR_40, ROOST_PP_TUPLE_EAT_4)(o(40, s), p, o, m)
# define ROOST_PP_FOR_40_I(s, p, o, m) ROOST_PP_IF(p(41, s), m, ROOST_PP_TUPLE_EAT_2)(41, s) ROOST_PP_IF(p(41, s), ROOST_PP_FOR_41, ROOST_PP_TUPLE_EAT_4)(o(41, s), p, o, m)
# define ROOST_PP_FOR_41_I(s, p, o, m) ROOST_PP_IF(p(42, s), m, ROOST_PP_TUPLE_EAT_2)(42, s) ROOST_PP_IF(p(42, s), ROOST_PP_FOR_42, ROOST_PP_TUPLE_EAT_4)(o(42, s), p, o, m)
# define ROOST_PP_FOR_42_I(s, p, o, m) ROOST_PP_IF(p(43, s), m, ROOST_PP_TUPLE_EAT_2)(43, s) ROOST_PP_IF(p(43, s), ROOST_PP_FOR_43, ROOST_PP_TUPLE_EAT_4)(o(43, s), p, o, m)
# define ROOST_PP_FOR_43_I(s, p, o, m) ROOST_PP_IF(p(44, s), m, ROOST_PP_TUPLE_EAT_2)(44, s) ROOST_PP_IF(p(44, s), ROOST_PP_FOR_44, ROOST_PP_TUPLE_EAT_4)(o(44, s), p, o, m)
# define ROOST_PP_FOR_44_I(s, p, o, m) ROOST_PP_IF(p(45, s), m, ROOST_PP_TUPLE_EAT_2)(45, s) ROOST_PP_IF(p(45, s), ROOST_PP_FOR_45, ROOST_PP_TUPLE_EAT_4)(o(45, s), p, o, m)
# define ROOST_PP_FOR_45_I(s, p, o, m) ROOST_PP_IF(p(46, s), m, ROOST_PP_TUPLE_EAT_2)(46, s) ROOST_PP_IF(p(46, s), ROOST_PP_FOR_46, ROOST_PP_TUPLE_EAT_4)(o(46, s), p, o, m)
# define ROOST_PP_FOR_46_I(s, p, o, m) ROOST_PP_IF(p(47, s), m, ROOST_PP_TUPLE_EAT_2)(47, s) ROOST_PP_IF(p(47, s), ROOST_PP_FOR_47, ROOST_PP_TUPLE_EAT_4)(o(47, s), p, o, m)
# define ROOST_PP_FOR_47_I(s, p, o, m) ROOST_PP_IF(p(48, s), m, ROOST_PP_TUPLE_EAT_2)(48, s) ROOST_PP_IF(p(48, s), ROOST_PP_FOR_48, ROOST_PP_TUPLE_EAT_4)(o(48, s), p, o, m)
# define ROOST_PP_FOR_48_I(s, p, o, m) ROOST_PP_IF(p(49, s), m, ROOST_PP_TUPLE_EAT_2)(49, s) ROOST_PP_IF(p(49, s), ROOST_PP_FOR_49, ROOST_PP_TUPLE_EAT_4)(o(49, s), p, o, m)
# define ROOST_PP_FOR_49_I(s, p, o, m) ROOST_PP_IF(p(50, s), m, ROOST_PP_TUPLE_EAT_2)(50, s) ROOST_PP_IF(p(50, s), ROOST_PP_FOR_50, ROOST_PP_TUPLE_EAT_4)(o(50, s), p, o, m)
# define ROOST_PP_FOR_50_I(s, p, o, m) ROOST_PP_IF(p(51, s), m, ROOST_PP_TUPLE_EAT_2)(51, s) ROOST_PP_IF(p(51, s), ROOST_PP_FOR_51, ROOST_PP_TUPLE_EAT_4)(o(51, s), p, o, m)
# define ROOST_PP_FOR_51_I(s, p, o, m) ROOST_PP_IF(p(52, s), m, ROOST_PP_TUPLE_EAT_2)(52, s) ROOST_PP_IF(p(52, s), ROOST_PP_FOR_52, ROOST_PP_TUPLE_EAT_4)(o(52, s), p, o, m)
# define ROOST_PP_FOR_52_I(s, p, o, m) ROOST_PP_IF(p(53, s), m, ROOST_PP_TUPLE_EAT_2)(53, s) ROOST_PP_IF(p(53, s), ROOST_PP_FOR_53, ROOST_PP_TUPLE_EAT_4)(o(53, s), p, o, m)
# define ROOST_PP_FOR_53_I(s, p, o, m) ROOST_PP_IF(p(54, s), m, ROOST_PP_TUPLE_EAT_2)(54, s) ROOST_PP_IF(p(54, s), ROOST_PP_FOR_54, ROOST_PP_TUPLE_EAT_4)(o(54, s), p, o, m)
# define ROOST_PP_FOR_54_I(s, p, o, m) ROOST_PP_IF(p(55, s), m, ROOST_PP_TUPLE_EAT_2)(55, s) ROOST_PP_IF(p(55, s), ROOST_PP_FOR_55, ROOST_PP_TUPLE_EAT_4)(o(55, s), p, o, m)
# define ROOST_PP_FOR_55_I(s, p, o, m) ROOST_PP_IF(p(56, s), m, ROOST_PP_TUPLE_EAT_2)(56, s) ROOST_PP_IF(p(56, s), ROOST_PP_FOR_56, ROOST_PP_TUPLE_EAT_4)(o(56, s), p, o, m)
# define ROOST_PP_FOR_56_I(s, p, o, m) ROOST_PP_IF(p(57, s), m, ROOST_PP_TUPLE_EAT_2)(57, s) ROOST_PP_IF(p(57, s), ROOST_PP_FOR_57, ROOST_PP_TUPLE_EAT_4)(o(57, s), p, o, m)
# define ROOST_PP_FOR_57_I(s, p, o, m) ROOST_PP_IF(p(58, s), m, ROOST_PP_TUPLE_EAT_2)(58, s) ROOST_PP_IF(p(58, s), ROOST_PP_FOR_58, ROOST_PP_TUPLE_EAT_4)(o(58, s), p, o, m)
# define ROOST_PP_FOR_58_I(s, p, o, m) ROOST_PP_IF(p(59, s), m, ROOST_PP_TUPLE_EAT_2)(59, s) ROOST_PP_IF(p(59, s), ROOST_PP_FOR_59, ROOST_PP_TUPLE_EAT_4)(o(59, s), p, o, m)
# define ROOST_PP_FOR_59_I(s, p, o, m) ROOST_PP_IF(p(60, s), m, ROOST_PP_TUPLE_EAT_2)(60, s) ROOST_PP_IF(p(60, s), ROOST_PP_FOR_60, ROOST_PP_TUPLE_EAT_4)(o(60, s), p, o, m)
# define ROOST_PP_FOR_60_I(s, p, o, m) ROOST_PP_IF(p(61, s), m, ROOST_PP_TUPLE_EAT_2)(61, s) ROOST_PP_IF(p(61, s), ROOST_PP_FOR_61, ROOST_PP_TUPLE_EAT_4)(o(61, s), p, o, m)
# define ROOST_PP_FOR_61_I(s, p, o, m) ROOST_PP_IF(p(62, s), m, ROOST_PP_TUPLE_EAT_2)(62, s) ROOST_PP_IF(p(62, s), ROOST_PP_FOR_62, ROOST_PP_TUPLE_EAT_4)(o(62, s), p, o, m)
# define ROOST_PP_FOR_62_I(s, p, o, m) ROOST_PP_IF(p(63, s), m, ROOST_PP_TUPLE_EAT_2)(63, s) ROOST_PP_IF(p(63, s), ROOST_PP_FOR_63, ROOST_PP_TUPLE_EAT_4)(o(63, s), p, o, m)
# define ROOST_PP_FOR_63_I(s, p, o, m) ROOST_PP_IF(p(64, s), m, ROOST_PP_TUPLE_EAT_2)(64, s) ROOST_PP_IF(p(64, s), ROOST_PP_FOR_64, ROOST_PP_TUPLE_EAT_4)(o(64, s), p, o, m)
# define ROOST_PP_FOR_64_I(s, p, o, m) ROOST_PP_IF(p(65, s), m, ROOST_PP_TUPLE_EAT_2)(65, s) ROOST_PP_IF(p(65, s), ROOST_PP_FOR_65, ROOST_PP_TUPLE_EAT_4)(o(65, s), p, o, m)
# define ROOST_PP_FOR_65_I(s, p, o, m) ROOST_PP_IF(p(66, s), m, ROOST_PP_TUPLE_EAT_2)(66, s) ROOST_PP_IF(p(66, s), ROOST_PP_FOR_66, ROOST_PP_TUPLE_EAT_4)(o(66, s), p, o, m)
# define ROOST_PP_FOR_66_I(s, p, o, m) ROOST_PP_IF(p(67, s), m, ROOST_PP_TUPLE_EAT_2)(67, s) ROOST_PP_IF(p(67, s), ROOST_PP_FOR_67, ROOST_PP_TUPLE_EAT_4)(o(67, s), p, o, m)
# define ROOST_PP_FOR_67_I(s, p, o, m) ROOST_PP_IF(p(68, s), m, ROOST_PP_TUPLE_EAT_2)(68, s) ROOST_PP_IF(p(68, s), ROOST_PP_FOR_68, ROOST_PP_TUPLE_EAT_4)(o(68, s), p, o, m)
# define ROOST_PP_FOR_68_I(s, p, o, m) ROOST_PP_IF(p(69, s), m, ROOST_PP_TUPLE_EAT_2)(69, s) ROOST_PP_IF(p(69, s), ROOST_PP_FOR_69, ROOST_PP_TUPLE_EAT_4)(o(69, s), p, o, m)
# define ROOST_PP_FOR_69_I(s, p, o, m) ROOST_PP_IF(p(70, s), m, ROOST_PP_TUPLE_EAT_2)(70, s) ROOST_PP_IF(p(70, s), ROOST_PP_FOR_70, ROOST_PP_TUPLE_EAT_4)(o(70, s), p, o, m)
# define ROOST_PP_FOR_70_I(s, p, o, m) ROOST_PP_IF(p(71, s), m, ROOST_PP_TUPLE_EAT_2)(71, s) ROOST_PP_IF(p(71, s), ROOST_PP_FOR_71, ROOST_PP_TUPLE_EAT_4)(o(71, s), p, o, m)
# define ROOST_PP_FOR_71_I(s, p, o, m) ROOST_PP_IF(p(72, s), m, ROOST_PP_TUPLE_EAT_2)(72, s) ROOST_PP_IF(p(72, s), ROOST_PP_FOR_72, ROOST_PP_TUPLE_EAT_4)(o(72, s), p, o, m)
# define ROOST_PP_FOR_72_I(s, p, o, m) ROOST_PP_IF(p(73, s), m, ROOST_PP_TUPLE_EAT_2)(73, s) ROOST_PP_IF(p(73, s), ROOST_PP_FOR_73, ROOST_PP_TUPLE_EAT_4)(o(73, s), p, o, m)
# define ROOST_PP_FOR_73_I(s, p, o, m) ROOST_PP_IF(p(74, s), m, ROOST_PP_TUPLE_EAT_2)(74, s) ROOST_PP_IF(p(74, s), ROOST_PP_FOR_74, ROOST_PP_TUPLE_EAT_4)(o(74, s), p, o, m)
# define ROOST_PP_FOR_74_I(s, p, o, m) ROOST_PP_IF(p(75, s), m, ROOST_PP_TUPLE_EAT_2)(75, s) ROOST_PP_IF(p(75, s), ROOST_PP_FOR_75, ROOST_PP_TUPLE_EAT_4)(o(75, s), p, o, m)
# define ROOST_PP_FOR_75_I(s, p, o, m) ROOST_PP_IF(p(76, s), m, ROOST_PP_TUPLE_EAT_2)(76, s) ROOST_PP_IF(p(76, s), ROOST_PP_FOR_76, ROOST_PP_TUPLE_EAT_4)(o(76, s), p, o, m)
# define ROOST_PP_FOR_76_I(s, p, o, m) ROOST_PP_IF(p(77, s), m, ROOST_PP_TUPLE_EAT_2)(77, s) ROOST_PP_IF(p(77, s), ROOST_PP_FOR_77, ROOST_PP_TUPLE_EAT_4)(o(77, s), p, o, m)
# define ROOST_PP_FOR_77_I(s, p, o, m) ROOST_PP_IF(p(78, s), m, ROOST_PP_TUPLE_EAT_2)(78, s) ROOST_PP_IF(p(78, s), ROOST_PP_FOR_78, ROOST_PP_TUPLE_EAT_4)(o(78, s), p, o, m)
# define ROOST_PP_FOR_78_I(s, p, o, m) ROOST_PP_IF(p(79, s), m, ROOST_PP_TUPLE_EAT_2)(79, s) ROOST_PP_IF(p(79, s), ROOST_PP_FOR_79, ROOST_PP_TUPLE_EAT_4)(o(79, s), p, o, m)
# define ROOST_PP_FOR_79_I(s, p, o, m) ROOST_PP_IF(p(80, s), m, ROOST_PP_TUPLE_EAT_2)(80, s) ROOST_PP_IF(p(80, s), ROOST_PP_FOR_80, ROOST_PP_TUPLE_EAT_4)(o(80, s), p, o, m)
# define ROOST_PP_FOR_80_I(s, p, o, m) ROOST_PP_IF(p(81, s), m, ROOST_PP_TUPLE_EAT_2)(81, s) ROOST_PP_IF(p(81, s), ROOST_PP_FOR_81, ROOST_PP_TUPLE_EAT_4)(o(81, s), p, o, m)
# define ROOST_PP_FOR_81_I(s, p, o, m) ROOST_PP_IF(p(82, s), m, ROOST_PP_TUPLE_EAT_2)(82, s) ROOST_PP_IF(p(82, s), ROOST_PP_FOR_82, ROOST_PP_TUPLE_EAT_4)(o(82, s), p, o, m)
# define ROOST_PP_FOR_82_I(s, p, o, m) ROOST_PP_IF(p(83, s), m, ROOST_PP_TUPLE_EAT_2)(83, s) ROOST_PP_IF(p(83, s), ROOST_PP_FOR_83, ROOST_PP_TUPLE_EAT_4)(o(83, s), p, o, m)
# define ROOST_PP_FOR_83_I(s, p, o, m) ROOST_PP_IF(p(84, s), m, ROOST_PP_TUPLE_EAT_2)(84, s) ROOST_PP_IF(p(84, s), ROOST_PP_FOR_84, ROOST_PP_TUPLE_EAT_4)(o(84, s), p, o, m)
# define ROOST_PP_FOR_84_I(s, p, o, m) ROOST_PP_IF(p(85, s), m, ROOST_PP_TUPLE_EAT_2)(85, s) ROOST_PP_IF(p(85, s), ROOST_PP_FOR_85, ROOST_PP_TUPLE_EAT_4)(o(85, s), p, o, m)
# define ROOST_PP_FOR_85_I(s, p, o, m) ROOST_PP_IF(p(86, s), m, ROOST_PP_TUPLE_EAT_2)(86, s) ROOST_PP_IF(p(86, s), ROOST_PP_FOR_86, ROOST_PP_TUPLE_EAT_4)(o(86, s), p, o, m)
# define ROOST_PP_FOR_86_I(s, p, o, m) ROOST_PP_IF(p(87, s), m, ROOST_PP_TUPLE_EAT_2)(87, s) ROOST_PP_IF(p(87, s), ROOST_PP_FOR_87, ROOST_PP_TUPLE_EAT_4)(o(87, s), p, o, m)
# define ROOST_PP_FOR_87_I(s, p, o, m) ROOST_PP_IF(p(88, s), m, ROOST_PP_TUPLE_EAT_2)(88, s) ROOST_PP_IF(p(88, s), ROOST_PP_FOR_88, ROOST_PP_TUPLE_EAT_4)(o(88, s), p, o, m)
# define ROOST_PP_FOR_88_I(s, p, o, m) ROOST_PP_IF(p(89, s), m, ROOST_PP_TUPLE_EAT_2)(89, s) ROOST_PP_IF(p(89, s), ROOST_PP_FOR_89, ROOST_PP_TUPLE_EAT_4)(o(89, s), p, o, m)
# define ROOST_PP_FOR_89_I(s, p, o, m) ROOST_PP_IF(p(90, s), m, ROOST_PP_TUPLE_EAT_2)(90, s) ROOST_PP_IF(p(90, s), ROOST_PP_FOR_90, ROOST_PP_TUPLE_EAT_4)(o(90, s), p, o, m)
# define ROOST_PP_FOR_90_I(s, p, o, m) ROOST_PP_IF(p(91, s), m, ROOST_PP_TUPLE_EAT_2)(91, s) ROOST_PP_IF(p(91, s), ROOST_PP_FOR_91, ROOST_PP_TUPLE_EAT_4)(o(91, s), p, o, m)
# define ROOST_PP_FOR_91_I(s, p, o, m) ROOST_PP_IF(p(92, s), m, ROOST_PP_TUPLE_EAT_2)(92, s) ROOST_PP_IF(p(92, s), ROOST_PP_FOR_92, ROOST_PP_TUPLE_EAT_4)(o(92, s), p, o, m)
# define ROOST_PP_FOR_92_I(s, p, o, m) ROOST_PP_IF(p(93, s), m, ROOST_PP_TUPLE_EAT_2)(93, s) ROOST_PP_IF(p(93, s), ROOST_PP_FOR_93, ROOST_PP_TUPLE_EAT_4)(o(93, s), p, o, m)
# define ROOST_PP_FOR_93_I(s, p, o, m) ROOST_PP_IF(p(94, s), m, ROOST_PP_TUPLE_EAT_2)(94, s) ROOST_PP_IF(p(94, s), ROOST_PP_FOR_94, ROOST_PP_TUPLE_EAT_4)(o(94, s), p, o, m)
# define ROOST_PP_FOR_94_I(s, p, o, m) ROOST_PP_IF(p(95, s), m, ROOST_PP_TUPLE_EAT_2)(95, s) ROOST_PP_IF(p(95, s), ROOST_PP_FOR_95, ROOST_PP_TUPLE_EAT_4)(o(95, s), p, o, m)
# define ROOST_PP_FOR_95_I(s, p, o, m) ROOST_PP_IF(p(96, s), m, ROOST_PP_TUPLE_EAT_2)(96, s) ROOST_PP_IF(p(96, s), ROOST_PP_FOR_96, ROOST_PP_TUPLE_EAT_4)(o(96, s), p, o, m)
# define ROOST_PP_FOR_96_I(s, p, o, m) ROOST_PP_IF(p(97, s), m, ROOST_PP_TUPLE_EAT_2)(97, s) ROOST_PP_IF(p(97, s), ROOST_PP_FOR_97, ROOST_PP_TUPLE_EAT_4)(o(97, s), p, o, m)
# define ROOST_PP_FOR_97_I(s, p, o, m) ROOST_PP_IF(p(98, s), m, ROOST_PP_TUPLE_EAT_2)(98, s) ROOST_PP_IF(p(98, s), ROOST_PP_FOR_98, ROOST_PP_TUPLE_EAT_4)(o(98, s), p, o, m)
# define ROOST_PP_FOR_98_I(s, p, o, m) ROOST_PP_IF(p(99, s), m, ROOST_PP_TUPLE_EAT_2)(99, s) ROOST_PP_IF(p(99, s), ROOST_PP_FOR_99, ROOST_PP_TUPLE_EAT_4)(o(99, s), p, o, m)
# define ROOST_PP_FOR_99_I(s, p, o, m) ROOST_PP_IF(p(100, s), m, ROOST_PP_TUPLE_EAT_2)(100, s) ROOST_PP_IF(p(100, s), ROOST_PP_FOR_100, ROOST_PP_TUPLE_EAT_4)(o(100, s), p, o, m)
# define ROOST_PP_FOR_100_I(s, p, o, m) ROOST_PP_IF(p(101, s), m, ROOST_PP_TUPLE_EAT_2)(101, s) ROOST_PP_IF(p(101, s), ROOST_PP_FOR_101, ROOST_PP_TUPLE_EAT_4)(o(101, s), p, o, m)
# define ROOST_PP_FOR_101_I(s, p, o, m) ROOST_PP_IF(p(102, s), m, ROOST_PP_TUPLE_EAT_2)(102, s) ROOST_PP_IF(p(102, s), ROOST_PP_FOR_102, ROOST_PP_TUPLE_EAT_4)(o(102, s), p, o, m)
# define ROOST_PP_FOR_102_I(s, p, o, m) ROOST_PP_IF(p(103, s), m, ROOST_PP_TUPLE_EAT_2)(103, s) ROOST_PP_IF(p(103, s), ROOST_PP_FOR_103, ROOST_PP_TUPLE_EAT_4)(o(103, s), p, o, m)
# define ROOST_PP_FOR_103_I(s, p, o, m) ROOST_PP_IF(p(104, s), m, ROOST_PP_TUPLE_EAT_2)(104, s) ROOST_PP_IF(p(104, s), ROOST_PP_FOR_104, ROOST_PP_TUPLE_EAT_4)(o(104, s), p, o, m)
# define ROOST_PP_FOR_104_I(s, p, o, m) ROOST_PP_IF(p(105, s), m, ROOST_PP_TUPLE_EAT_2)(105, s) ROOST_PP_IF(p(105, s), ROOST_PP_FOR_105, ROOST_PP_TUPLE_EAT_4)(o(105, s), p, o, m)
# define ROOST_PP_FOR_105_I(s, p, o, m) ROOST_PP_IF(p(106, s), m, ROOST_PP_TUPLE_EAT_2)(106, s) ROOST_PP_IF(p(106, s), ROOST_PP_FOR_106, ROOST_PP_TUPLE_EAT_4)(o(106, s), p, o, m)
# define ROOST_PP_FOR_106_I(s, p, o, m) ROOST_PP_IF(p(107, s), m, ROOST_PP_TUPLE_EAT_2)(107, s) ROOST_PP_IF(p(107, s), ROOST_PP_FOR_107, ROOST_PP_TUPLE_EAT_4)(o(107, s), p, o, m)
# define ROOST_PP_FOR_107_I(s, p, o, m) ROOST_PP_IF(p(108, s), m, ROOST_PP_TUPLE_EAT_2)(108, s) ROOST_PP_IF(p(108, s), ROOST_PP_FOR_108, ROOST_PP_TUPLE_EAT_4)(o(108, s), p, o, m)
# define ROOST_PP_FOR_108_I(s, p, o, m) ROOST_PP_IF(p(109, s), m, ROOST_PP_TUPLE_EAT_2)(109, s) ROOST_PP_IF(p(109, s), ROOST_PP_FOR_109, ROOST_PP_TUPLE_EAT_4)(o(109, s), p, o, m)
# define ROOST_PP_FOR_109_I(s, p, o, m) ROOST_PP_IF(p(110, s), m, ROOST_PP_TUPLE_EAT_2)(110, s) ROOST_PP_IF(p(110, s), ROOST_PP_FOR_110, ROOST_PP_TUPLE_EAT_4)(o(110, s), p, o, m)
# define ROOST_PP_FOR_110_I(s, p, o, m) ROOST_PP_IF(p(111, s), m, ROOST_PP_TUPLE_EAT_2)(111, s) ROOST_PP_IF(p(111, s), ROOST_PP_FOR_111, ROOST_PP_TUPLE_EAT_4)(o(111, s), p, o, m)
# define ROOST_PP_FOR_111_I(s, p, o, m) ROOST_PP_IF(p(112, s), m, ROOST_PP_TUPLE_EAT_2)(112, s) ROOST_PP_IF(p(112, s), ROOST_PP_FOR_112, ROOST_PP_TUPLE_EAT_4)(o(112, s), p, o, m)
# define ROOST_PP_FOR_112_I(s, p, o, m) ROOST_PP_IF(p(113, s), m, ROOST_PP_TUPLE_EAT_2)(113, s) ROOST_PP_IF(p(113, s), ROOST_PP_FOR_113, ROOST_PP_TUPLE_EAT_4)(o(113, s), p, o, m)
# define ROOST_PP_FOR_113_I(s, p, o, m) ROOST_PP_IF(p(114, s), m, ROOST_PP_TUPLE_EAT_2)(114, s) ROOST_PP_IF(p(114, s), ROOST_PP_FOR_114, ROOST_PP_TUPLE_EAT_4)(o(114, s), p, o, m)
# define ROOST_PP_FOR_114_I(s, p, o, m) ROOST_PP_IF(p(115, s), m, ROOST_PP_TUPLE_EAT_2)(115, s) ROOST_PP_IF(p(115, s), ROOST_PP_FOR_115, ROOST_PP_TUPLE_EAT_4)(o(115, s), p, o, m)
# define ROOST_PP_FOR_115_I(s, p, o, m) ROOST_PP_IF(p(116, s), m, ROOST_PP_TUPLE_EAT_2)(116, s) ROOST_PP_IF(p(116, s), ROOST_PP_FOR_116, ROOST_PP_TUPLE_EAT_4)(o(116, s), p, o, m)
# define ROOST_PP_FOR_116_I(s, p, o, m) ROOST_PP_IF(p(117, s), m, ROOST_PP_TUPLE_EAT_2)(117, s) ROOST_PP_IF(p(117, s), ROOST_PP_FOR_117, ROOST_PP_TUPLE_EAT_4)(o(117, s), p, o, m)
# define ROOST_PP_FOR_117_I(s, p, o, m) ROOST_PP_IF(p(118, s), m, ROOST_PP_TUPLE_EAT_2)(118, s) ROOST_PP_IF(p(118, s), ROOST_PP_FOR_118, ROOST_PP_TUPLE_EAT_4)(o(118, s), p, o, m)
# define ROOST_PP_FOR_118_I(s, p, o, m) ROOST_PP_IF(p(119, s), m, ROOST_PP_TUPLE_EAT_2)(119, s) ROOST_PP_IF(p(119, s), ROOST_PP_FOR_119, ROOST_PP_TUPLE_EAT_4)(o(119, s), p, o, m)
# define ROOST_PP_FOR_119_I(s, p, o, m) ROOST_PP_IF(p(120, s), m, ROOST_PP_TUPLE_EAT_2)(120, s) ROOST_PP_IF(p(120, s), ROOST_PP_FOR_120, ROOST_PP_TUPLE_EAT_4)(o(120, s), p, o, m)
# define ROOST_PP_FOR_120_I(s, p, o, m) ROOST_PP_IF(p(121, s), m, ROOST_PP_TUPLE_EAT_2)(121, s) ROOST_PP_IF(p(121, s), ROOST_PP_FOR_121, ROOST_PP_TUPLE_EAT_4)(o(121, s), p, o, m)
# define ROOST_PP_FOR_121_I(s, p, o, m) ROOST_PP_IF(p(122, s), m, ROOST_PP_TUPLE_EAT_2)(122, s) ROOST_PP_IF(p(122, s), ROOST_PP_FOR_122, ROOST_PP_TUPLE_EAT_4)(o(122, s), p, o, m)
# define ROOST_PP_FOR_122_I(s, p, o, m) ROOST_PP_IF(p(123, s), m, ROOST_PP_TUPLE_EAT_2)(123, s) ROOST_PP_IF(p(123, s), ROOST_PP_FOR_123, ROOST_PP_TUPLE_EAT_4)(o(123, s), p, o, m)
# define ROOST_PP_FOR_123_I(s, p, o, m) ROOST_PP_IF(p(124, s), m, ROOST_PP_TUPLE_EAT_2)(124, s) ROOST_PP_IF(p(124, s), ROOST_PP_FOR_124, ROOST_PP_TUPLE_EAT_4)(o(124, s), p, o, m)
# define ROOST_PP_FOR_124_I(s, p, o, m) ROOST_PP_IF(p(125, s), m, ROOST_PP_TUPLE_EAT_2)(125, s) ROOST_PP_IF(p(125, s), ROOST_PP_FOR_125, ROOST_PP_TUPLE_EAT_4)(o(125, s), p, o, m)
# define ROOST_PP_FOR_125_I(s, p, o, m) ROOST_PP_IF(p(126, s), m, ROOST_PP_TUPLE_EAT_2)(126, s) ROOST_PP_IF(p(126, s), ROOST_PP_FOR_126, ROOST_PP_TUPLE_EAT_4)(o(126, s), p, o, m)
# define ROOST_PP_FOR_126_I(s, p, o, m) ROOST_PP_IF(p(127, s), m, ROOST_PP_TUPLE_EAT_2)(127, s) ROOST_PP_IF(p(127, s), ROOST_PP_FOR_127, ROOST_PP_TUPLE_EAT_4)(o(127, s), p, o, m)
# define ROOST_PP_FOR_127_I(s, p, o, m) ROOST_PP_IF(p(128, s), m, ROOST_PP_TUPLE_EAT_2)(128, s) ROOST_PP_IF(p(128, s), ROOST_PP_FOR_128, ROOST_PP_TUPLE_EAT_4)(o(128, s), p, o, m)
# define ROOST_PP_FOR_128_I(s, p, o, m) ROOST_PP_IF(p(129, s), m, ROOST_PP_TUPLE_EAT_2)(129, s) ROOST_PP_IF(p(129, s), ROOST_PP_FOR_129, ROOST_PP_TUPLE_EAT_4)(o(129, s), p, o, m)
# define ROOST_PP_FOR_129_I(s, p, o, m) ROOST_PP_IF(p(130, s), m, ROOST_PP_TUPLE_EAT_2)(130, s) ROOST_PP_IF(p(130, s), ROOST_PP_FOR_130, ROOST_PP_TUPLE_EAT_4)(o(130, s), p, o, m)
# define ROOST_PP_FOR_130_I(s, p, o, m) ROOST_PP_IF(p(131, s), m, ROOST_PP_TUPLE_EAT_2)(131, s) ROOST_PP_IF(p(131, s), ROOST_PP_FOR_131, ROOST_PP_TUPLE_EAT_4)(o(131, s), p, o, m)
# define ROOST_PP_FOR_131_I(s, p, o, m) ROOST_PP_IF(p(132, s), m, ROOST_PP_TUPLE_EAT_2)(132, s) ROOST_PP_IF(p(132, s), ROOST_PP_FOR_132, ROOST_PP_TUPLE_EAT_4)(o(132, s), p, o, m)
# define ROOST_PP_FOR_132_I(s, p, o, m) ROOST_PP_IF(p(133, s), m, ROOST_PP_TUPLE_EAT_2)(133, s) ROOST_PP_IF(p(133, s), ROOST_PP_FOR_133, ROOST_PP_TUPLE_EAT_4)(o(133, s), p, o, m)
# define ROOST_PP_FOR_133_I(s, p, o, m) ROOST_PP_IF(p(134, s), m, ROOST_PP_TUPLE_EAT_2)(134, s) ROOST_PP_IF(p(134, s), ROOST_PP_FOR_134, ROOST_PP_TUPLE_EAT_4)(o(134, s), p, o, m)
# define ROOST_PP_FOR_134_I(s, p, o, m) ROOST_PP_IF(p(135, s), m, ROOST_PP_TUPLE_EAT_2)(135, s) ROOST_PP_IF(p(135, s), ROOST_PP_FOR_135, ROOST_PP_TUPLE_EAT_4)(o(135, s), p, o, m)
# define ROOST_PP_FOR_135_I(s, p, o, m) ROOST_PP_IF(p(136, s), m, ROOST_PP_TUPLE_EAT_2)(136, s) ROOST_PP_IF(p(136, s), ROOST_PP_FOR_136, ROOST_PP_TUPLE_EAT_4)(o(136, s), p, o, m)
# define ROOST_PP_FOR_136_I(s, p, o, m) ROOST_PP_IF(p(137, s), m, ROOST_PP_TUPLE_EAT_2)(137, s) ROOST_PP_IF(p(137, s), ROOST_PP_FOR_137, ROOST_PP_TUPLE_EAT_4)(o(137, s), p, o, m)
# define ROOST_PP_FOR_137_I(s, p, o, m) ROOST_PP_IF(p(138, s), m, ROOST_PP_TUPLE_EAT_2)(138, s) ROOST_PP_IF(p(138, s), ROOST_PP_FOR_138, ROOST_PP_TUPLE_EAT_4)(o(138, s), p, o, m)
# define ROOST_PP_FOR_138_I(s, p, o, m) ROOST_PP_IF(p(139, s), m, ROOST_PP_TUPLE_EAT_2)(139, s) ROOST_PP_IF(p(139, s), ROOST_PP_FOR_139, ROOST_PP_TUPLE_EAT_4)(o(139, s), p, o, m)
# define ROOST_PP_FOR_139_I(s, p, o, m) ROOST_PP_IF(p(140, s), m, ROOST_PP_TUPLE_EAT_2)(140, s) ROOST_PP_IF(p(140, s), ROOST_PP_FOR_140, ROOST_PP_TUPLE_EAT_4)(o(140, s), p, o, m)
# define ROOST_PP_FOR_140_I(s, p, o, m) ROOST_PP_IF(p(141, s), m, ROOST_PP_TUPLE_EAT_2)(141, s) ROOST_PP_IF(p(141, s), ROOST_PP_FOR_141, ROOST_PP_TUPLE_EAT_4)(o(141, s), p, o, m)
# define ROOST_PP_FOR_141_I(s, p, o, m) ROOST_PP_IF(p(142, s), m, ROOST_PP_TUPLE_EAT_2)(142, s) ROOST_PP_IF(p(142, s), ROOST_PP_FOR_142, ROOST_PP_TUPLE_EAT_4)(o(142, s), p, o, m)
# define ROOST_PP_FOR_142_I(s, p, o, m) ROOST_PP_IF(p(143, s), m, ROOST_PP_TUPLE_EAT_2)(143, s) ROOST_PP_IF(p(143, s), ROOST_PP_FOR_143, ROOST_PP_TUPLE_EAT_4)(o(143, s), p, o, m)
# define ROOST_PP_FOR_143_I(s, p, o, m) ROOST_PP_IF(p(144, s), m, ROOST_PP_TUPLE_EAT_2)(144, s) ROOST_PP_IF(p(144, s), ROOST_PP_FOR_144, ROOST_PP_TUPLE_EAT_4)(o(144, s), p, o, m)
# define ROOST_PP_FOR_144_I(s, p, o, m) ROOST_PP_IF(p(145, s), m, ROOST_PP_TUPLE_EAT_2)(145, s) ROOST_PP_IF(p(145, s), ROOST_PP_FOR_145, ROOST_PP_TUPLE_EAT_4)(o(145, s), p, o, m)
# define ROOST_PP_FOR_145_I(s, p, o, m) ROOST_PP_IF(p(146, s), m, ROOST_PP_TUPLE_EAT_2)(146, s) ROOST_PP_IF(p(146, s), ROOST_PP_FOR_146, ROOST_PP_TUPLE_EAT_4)(o(146, s), p, o, m)
# define ROOST_PP_FOR_146_I(s, p, o, m) ROOST_PP_IF(p(147, s), m, ROOST_PP_TUPLE_EAT_2)(147, s) ROOST_PP_IF(p(147, s), ROOST_PP_FOR_147, ROOST_PP_TUPLE_EAT_4)(o(147, s), p, o, m)
# define ROOST_PP_FOR_147_I(s, p, o, m) ROOST_PP_IF(p(148, s), m, ROOST_PP_TUPLE_EAT_2)(148, s) ROOST_PP_IF(p(148, s), ROOST_PP_FOR_148, ROOST_PP_TUPLE_EAT_4)(o(148, s), p, o, m)
# define ROOST_PP_FOR_148_I(s, p, o, m) ROOST_PP_IF(p(149, s), m, ROOST_PP_TUPLE_EAT_2)(149, s) ROOST_PP_IF(p(149, s), ROOST_PP_FOR_149, ROOST_PP_TUPLE_EAT_4)(o(149, s), p, o, m)
# define ROOST_PP_FOR_149_I(s, p, o, m) ROOST_PP_IF(p(150, s), m, ROOST_PP_TUPLE_EAT_2)(150, s) ROOST_PP_IF(p(150, s), ROOST_PP_FOR_150, ROOST_PP_TUPLE_EAT_4)(o(150, s), p, o, m)
# define ROOST_PP_FOR_150_I(s, p, o, m) ROOST_PP_IF(p(151, s), m, ROOST_PP_TUPLE_EAT_2)(151, s) ROOST_PP_IF(p(151, s), ROOST_PP_FOR_151, ROOST_PP_TUPLE_EAT_4)(o(151, s), p, o, m)
# define ROOST_PP_FOR_151_I(s, p, o, m) ROOST_PP_IF(p(152, s), m, ROOST_PP_TUPLE_EAT_2)(152, s) ROOST_PP_IF(p(152, s), ROOST_PP_FOR_152, ROOST_PP_TUPLE_EAT_4)(o(152, s), p, o, m)
# define ROOST_PP_FOR_152_I(s, p, o, m) ROOST_PP_IF(p(153, s), m, ROOST_PP_TUPLE_EAT_2)(153, s) ROOST_PP_IF(p(153, s), ROOST_PP_FOR_153, ROOST_PP_TUPLE_EAT_4)(o(153, s), p, o, m)
# define ROOST_PP_FOR_153_I(s, p, o, m) ROOST_PP_IF(p(154, s), m, ROOST_PP_TUPLE_EAT_2)(154, s) ROOST_PP_IF(p(154, s), ROOST_PP_FOR_154, ROOST_PP_TUPLE_EAT_4)(o(154, s), p, o, m)
# define ROOST_PP_FOR_154_I(s, p, o, m) ROOST_PP_IF(p(155, s), m, ROOST_PP_TUPLE_EAT_2)(155, s) ROOST_PP_IF(p(155, s), ROOST_PP_FOR_155, ROOST_PP_TUPLE_EAT_4)(o(155, s), p, o, m)
# define ROOST_PP_FOR_155_I(s, p, o, m) ROOST_PP_IF(p(156, s), m, ROOST_PP_TUPLE_EAT_2)(156, s) ROOST_PP_IF(p(156, s), ROOST_PP_FOR_156, ROOST_PP_TUPLE_EAT_4)(o(156, s), p, o, m)
# define ROOST_PP_FOR_156_I(s, p, o, m) ROOST_PP_IF(p(157, s), m, ROOST_PP_TUPLE_EAT_2)(157, s) ROOST_PP_IF(p(157, s), ROOST_PP_FOR_157, ROOST_PP_TUPLE_EAT_4)(o(157, s), p, o, m)
# define ROOST_PP_FOR_157_I(s, p, o, m) ROOST_PP_IF(p(158, s), m, ROOST_PP_TUPLE_EAT_2)(158, s) ROOST_PP_IF(p(158, s), ROOST_PP_FOR_158, ROOST_PP_TUPLE_EAT_4)(o(158, s), p, o, m)
# define ROOST_PP_FOR_158_I(s, p, o, m) ROOST_PP_IF(p(159, s), m, ROOST_PP_TUPLE_EAT_2)(159, s) ROOST_PP_IF(p(159, s), ROOST_PP_FOR_159, ROOST_PP_TUPLE_EAT_4)(o(159, s), p, o, m)
# define ROOST_PP_FOR_159_I(s, p, o, m) ROOST_PP_IF(p(160, s), m, ROOST_PP_TUPLE_EAT_2)(160, s) ROOST_PP_IF(p(160, s), ROOST_PP_FOR_160, ROOST_PP_TUPLE_EAT_4)(o(160, s), p, o, m)
# define ROOST_PP_FOR_160_I(s, p, o, m) ROOST_PP_IF(p(161, s), m, ROOST_PP_TUPLE_EAT_2)(161, s) ROOST_PP_IF(p(161, s), ROOST_PP_FOR_161, ROOST_PP_TUPLE_EAT_4)(o(161, s), p, o, m)
# define ROOST_PP_FOR_161_I(s, p, o, m) ROOST_PP_IF(p(162, s), m, ROOST_PP_TUPLE_EAT_2)(162, s) ROOST_PP_IF(p(162, s), ROOST_PP_FOR_162, ROOST_PP_TUPLE_EAT_4)(o(162, s), p, o, m)
# define ROOST_PP_FOR_162_I(s, p, o, m) ROOST_PP_IF(p(163, s), m, ROOST_PP_TUPLE_EAT_2)(163, s) ROOST_PP_IF(p(163, s), ROOST_PP_FOR_163, ROOST_PP_TUPLE_EAT_4)(o(163, s), p, o, m)
# define ROOST_PP_FOR_163_I(s, p, o, m) ROOST_PP_IF(p(164, s), m, ROOST_PP_TUPLE_EAT_2)(164, s) ROOST_PP_IF(p(164, s), ROOST_PP_FOR_164, ROOST_PP_TUPLE_EAT_4)(o(164, s), p, o, m)
# define ROOST_PP_FOR_164_I(s, p, o, m) ROOST_PP_IF(p(165, s), m, ROOST_PP_TUPLE_EAT_2)(165, s) ROOST_PP_IF(p(165, s), ROOST_PP_FOR_165, ROOST_PP_TUPLE_EAT_4)(o(165, s), p, o, m)
# define ROOST_PP_FOR_165_I(s, p, o, m) ROOST_PP_IF(p(166, s), m, ROOST_PP_TUPLE_EAT_2)(166, s) ROOST_PP_IF(p(166, s), ROOST_PP_FOR_166, ROOST_PP_TUPLE_EAT_4)(o(166, s), p, o, m)
# define ROOST_PP_FOR_166_I(s, p, o, m) ROOST_PP_IF(p(167, s), m, ROOST_PP_TUPLE_EAT_2)(167, s) ROOST_PP_IF(p(167, s), ROOST_PP_FOR_167, ROOST_PP_TUPLE_EAT_4)(o(167, s), p, o, m)
# define ROOST_PP_FOR_167_I(s, p, o, m) ROOST_PP_IF(p(168, s), m, ROOST_PP_TUPLE_EAT_2)(168, s) ROOST_PP_IF(p(168, s), ROOST_PP_FOR_168, ROOST_PP_TUPLE_EAT_4)(o(168, s), p, o, m)
# define ROOST_PP_FOR_168_I(s, p, o, m) ROOST_PP_IF(p(169, s), m, ROOST_PP_TUPLE_EAT_2)(169, s) ROOST_PP_IF(p(169, s), ROOST_PP_FOR_169, ROOST_PP_TUPLE_EAT_4)(o(169, s), p, o, m)
# define ROOST_PP_FOR_169_I(s, p, o, m) ROOST_PP_IF(p(170, s), m, ROOST_PP_TUPLE_EAT_2)(170, s) ROOST_PP_IF(p(170, s), ROOST_PP_FOR_170, ROOST_PP_TUPLE_EAT_4)(o(170, s), p, o, m)
# define ROOST_PP_FOR_170_I(s, p, o, m) ROOST_PP_IF(p(171, s), m, ROOST_PP_TUPLE_EAT_2)(171, s) ROOST_PP_IF(p(171, s), ROOST_PP_FOR_171, ROOST_PP_TUPLE_EAT_4)(o(171, s), p, o, m)
# define ROOST_PP_FOR_171_I(s, p, o, m) ROOST_PP_IF(p(172, s), m, ROOST_PP_TUPLE_EAT_2)(172, s) ROOST_PP_IF(p(172, s), ROOST_PP_FOR_172, ROOST_PP_TUPLE_EAT_4)(o(172, s), p, o, m)
# define ROOST_PP_FOR_172_I(s, p, o, m) ROOST_PP_IF(p(173, s), m, ROOST_PP_TUPLE_EAT_2)(173, s) ROOST_PP_IF(p(173, s), ROOST_PP_FOR_173, ROOST_PP_TUPLE_EAT_4)(o(173, s), p, o, m)
# define ROOST_PP_FOR_173_I(s, p, o, m) ROOST_PP_IF(p(174, s), m, ROOST_PP_TUPLE_EAT_2)(174, s) ROOST_PP_IF(p(174, s), ROOST_PP_FOR_174, ROOST_PP_TUPLE_EAT_4)(o(174, s), p, o, m)
# define ROOST_PP_FOR_174_I(s, p, o, m) ROOST_PP_IF(p(175, s), m, ROOST_PP_TUPLE_EAT_2)(175, s) ROOST_PP_IF(p(175, s), ROOST_PP_FOR_175, ROOST_PP_TUPLE_EAT_4)(o(175, s), p, o, m)
# define ROOST_PP_FOR_175_I(s, p, o, m) ROOST_PP_IF(p(176, s), m, ROOST_PP_TUPLE_EAT_2)(176, s) ROOST_PP_IF(p(176, s), ROOST_PP_FOR_176, ROOST_PP_TUPLE_EAT_4)(o(176, s), p, o, m)
# define ROOST_PP_FOR_176_I(s, p, o, m) ROOST_PP_IF(p(177, s), m, ROOST_PP_TUPLE_EAT_2)(177, s) ROOST_PP_IF(p(177, s), ROOST_PP_FOR_177, ROOST_PP_TUPLE_EAT_4)(o(177, s), p, o, m)
# define ROOST_PP_FOR_177_I(s, p, o, m) ROOST_PP_IF(p(178, s), m, ROOST_PP_TUPLE_EAT_2)(178, s) ROOST_PP_IF(p(178, s), ROOST_PP_FOR_178, ROOST_PP_TUPLE_EAT_4)(o(178, s), p, o, m)
# define ROOST_PP_FOR_178_I(s, p, o, m) ROOST_PP_IF(p(179, s), m, ROOST_PP_TUPLE_EAT_2)(179, s) ROOST_PP_IF(p(179, s), ROOST_PP_FOR_179, ROOST_PP_TUPLE_EAT_4)(o(179, s), p, o, m)
# define ROOST_PP_FOR_179_I(s, p, o, m) ROOST_PP_IF(p(180, s), m, ROOST_PP_TUPLE_EAT_2)(180, s) ROOST_PP_IF(p(180, s), ROOST_PP_FOR_180, ROOST_PP_TUPLE_EAT_4)(o(180, s), p, o, m)
# define ROOST_PP_FOR_180_I(s, p, o, m) ROOST_PP_IF(p(181, s), m, ROOST_PP_TUPLE_EAT_2)(181, s) ROOST_PP_IF(p(181, s), ROOST_PP_FOR_181, ROOST_PP_TUPLE_EAT_4)(o(181, s), p, o, m)
# define ROOST_PP_FOR_181_I(s, p, o, m) ROOST_PP_IF(p(182, s), m, ROOST_PP_TUPLE_EAT_2)(182, s) ROOST_PP_IF(p(182, s), ROOST_PP_FOR_182, ROOST_PP_TUPLE_EAT_4)(o(182, s), p, o, m)
# define ROOST_PP_FOR_182_I(s, p, o, m) ROOST_PP_IF(p(183, s), m, ROOST_PP_TUPLE_EAT_2)(183, s) ROOST_PP_IF(p(183, s), ROOST_PP_FOR_183, ROOST_PP_TUPLE_EAT_4)(o(183, s), p, o, m)
# define ROOST_PP_FOR_183_I(s, p, o, m) ROOST_PP_IF(p(184, s), m, ROOST_PP_TUPLE_EAT_2)(184, s) ROOST_PP_IF(p(184, s), ROOST_PP_FOR_184, ROOST_PP_TUPLE_EAT_4)(o(184, s), p, o, m)
# define ROOST_PP_FOR_184_I(s, p, o, m) ROOST_PP_IF(p(185, s), m, ROOST_PP_TUPLE_EAT_2)(185, s) ROOST_PP_IF(p(185, s), ROOST_PP_FOR_185, ROOST_PP_TUPLE_EAT_4)(o(185, s), p, o, m)
# define ROOST_PP_FOR_185_I(s, p, o, m) ROOST_PP_IF(p(186, s), m, ROOST_PP_TUPLE_EAT_2)(186, s) ROOST_PP_IF(p(186, s), ROOST_PP_FOR_186, ROOST_PP_TUPLE_EAT_4)(o(186, s), p, o, m)
# define ROOST_PP_FOR_186_I(s, p, o, m) ROOST_PP_IF(p(187, s), m, ROOST_PP_TUPLE_EAT_2)(187, s) ROOST_PP_IF(p(187, s), ROOST_PP_FOR_187, ROOST_PP_TUPLE_EAT_4)(o(187, s), p, o, m)
# define ROOST_PP_FOR_187_I(s, p, o, m) ROOST_PP_IF(p(188, s), m, ROOST_PP_TUPLE_EAT_2)(188, s) ROOST_PP_IF(p(188, s), ROOST_PP_FOR_188, ROOST_PP_TUPLE_EAT_4)(o(188, s), p, o, m)
# define ROOST_PP_FOR_188_I(s, p, o, m) ROOST_PP_IF(p(189, s), m, ROOST_PP_TUPLE_EAT_2)(189, s) ROOST_PP_IF(p(189, s), ROOST_PP_FOR_189, ROOST_PP_TUPLE_EAT_4)(o(189, s), p, o, m)
# define ROOST_PP_FOR_189_I(s, p, o, m) ROOST_PP_IF(p(190, s), m, ROOST_PP_TUPLE_EAT_2)(190, s) ROOST_PP_IF(p(190, s), ROOST_PP_FOR_190, ROOST_PP_TUPLE_EAT_4)(o(190, s), p, o, m)
# define ROOST_PP_FOR_190_I(s, p, o, m) ROOST_PP_IF(p(191, s), m, ROOST_PP_TUPLE_EAT_2)(191, s) ROOST_PP_IF(p(191, s), ROOST_PP_FOR_191, ROOST_PP_TUPLE_EAT_4)(o(191, s), p, o, m)
# define ROOST_PP_FOR_191_I(s, p, o, m) ROOST_PP_IF(p(192, s), m, ROOST_PP_TUPLE_EAT_2)(192, s) ROOST_PP_IF(p(192, s), ROOST_PP_FOR_192, ROOST_PP_TUPLE_EAT_4)(o(192, s), p, o, m)
# define ROOST_PP_FOR_192_I(s, p, o, m) ROOST_PP_IF(p(193, s), m, ROOST_PP_TUPLE_EAT_2)(193, s) ROOST_PP_IF(p(193, s), ROOST_PP_FOR_193, ROOST_PP_TUPLE_EAT_4)(o(193, s), p, o, m)
# define ROOST_PP_FOR_193_I(s, p, o, m) ROOST_PP_IF(p(194, s), m, ROOST_PP_TUPLE_EAT_2)(194, s) ROOST_PP_IF(p(194, s), ROOST_PP_FOR_194, ROOST_PP_TUPLE_EAT_4)(o(194, s), p, o, m)
# define ROOST_PP_FOR_194_I(s, p, o, m) ROOST_PP_IF(p(195, s), m, ROOST_PP_TUPLE_EAT_2)(195, s) ROOST_PP_IF(p(195, s), ROOST_PP_FOR_195, ROOST_PP_TUPLE_EAT_4)(o(195, s), p, o, m)
# define ROOST_PP_FOR_195_I(s, p, o, m) ROOST_PP_IF(p(196, s), m, ROOST_PP_TUPLE_EAT_2)(196, s) ROOST_PP_IF(p(196, s), ROOST_PP_FOR_196, ROOST_PP_TUPLE_EAT_4)(o(196, s), p, o, m)
# define ROOST_PP_FOR_196_I(s, p, o, m) ROOST_PP_IF(p(197, s), m, ROOST_PP_TUPLE_EAT_2)(197, s) ROOST_PP_IF(p(197, s), ROOST_PP_FOR_197, ROOST_PP_TUPLE_EAT_4)(o(197, s), p, o, m)
# define ROOST_PP_FOR_197_I(s, p, o, m) ROOST_PP_IF(p(198, s), m, ROOST_PP_TUPLE_EAT_2)(198, s) ROOST_PP_IF(p(198, s), ROOST_PP_FOR_198, ROOST_PP_TUPLE_EAT_4)(o(198, s), p, o, m)
# define ROOST_PP_FOR_198_I(s, p, o, m) ROOST_PP_IF(p(199, s), m, ROOST_PP_TUPLE_EAT_2)(199, s) ROOST_PP_IF(p(199, s), ROOST_PP_FOR_199, ROOST_PP_TUPLE_EAT_4)(o(199, s), p, o, m)
# define ROOST_PP_FOR_199_I(s, p, o, m) ROOST_PP_IF(p(200, s), m, ROOST_PP_TUPLE_EAT_2)(200, s) ROOST_PP_IF(p(200, s), ROOST_PP_FOR_200, ROOST_PP_TUPLE_EAT_4)(o(200, s), p, o, m)
# define ROOST_PP_FOR_200_I(s, p, o, m) ROOST_PP_IF(p(201, s), m, ROOST_PP_TUPLE_EAT_2)(201, s) ROOST_PP_IF(p(201, s), ROOST_PP_FOR_201, ROOST_PP_TUPLE_EAT_4)(o(201, s), p, o, m)
# define ROOST_PP_FOR_201_I(s, p, o, m) ROOST_PP_IF(p(202, s), m, ROOST_PP_TUPLE_EAT_2)(202, s) ROOST_PP_IF(p(202, s), ROOST_PP_FOR_202, ROOST_PP_TUPLE_EAT_4)(o(202, s), p, o, m)
# define ROOST_PP_FOR_202_I(s, p, o, m) ROOST_PP_IF(p(203, s), m, ROOST_PP_TUPLE_EAT_2)(203, s) ROOST_PP_IF(p(203, s), ROOST_PP_FOR_203, ROOST_PP_TUPLE_EAT_4)(o(203, s), p, o, m)
# define ROOST_PP_FOR_203_I(s, p, o, m) ROOST_PP_IF(p(204, s), m, ROOST_PP_TUPLE_EAT_2)(204, s) ROOST_PP_IF(p(204, s), ROOST_PP_FOR_204, ROOST_PP_TUPLE_EAT_4)(o(204, s), p, o, m)
# define ROOST_PP_FOR_204_I(s, p, o, m) ROOST_PP_IF(p(205, s), m, ROOST_PP_TUPLE_EAT_2)(205, s) ROOST_PP_IF(p(205, s), ROOST_PP_FOR_205, ROOST_PP_TUPLE_EAT_4)(o(205, s), p, o, m)
# define ROOST_PP_FOR_205_I(s, p, o, m) ROOST_PP_IF(p(206, s), m, ROOST_PP_TUPLE_EAT_2)(206, s) ROOST_PP_IF(p(206, s), ROOST_PP_FOR_206, ROOST_PP_TUPLE_EAT_4)(o(206, s), p, o, m)
# define ROOST_PP_FOR_206_I(s, p, o, m) ROOST_PP_IF(p(207, s), m, ROOST_PP_TUPLE_EAT_2)(207, s) ROOST_PP_IF(p(207, s), ROOST_PP_FOR_207, ROOST_PP_TUPLE_EAT_4)(o(207, s), p, o, m)
# define ROOST_PP_FOR_207_I(s, p, o, m) ROOST_PP_IF(p(208, s), m, ROOST_PP_TUPLE_EAT_2)(208, s) ROOST_PP_IF(p(208, s), ROOST_PP_FOR_208, ROOST_PP_TUPLE_EAT_4)(o(208, s), p, o, m)
# define ROOST_PP_FOR_208_I(s, p, o, m) ROOST_PP_IF(p(209, s), m, ROOST_PP_TUPLE_EAT_2)(209, s) ROOST_PP_IF(p(209, s), ROOST_PP_FOR_209, ROOST_PP_TUPLE_EAT_4)(o(209, s), p, o, m)
# define ROOST_PP_FOR_209_I(s, p, o, m) ROOST_PP_IF(p(210, s), m, ROOST_PP_TUPLE_EAT_2)(210, s) ROOST_PP_IF(p(210, s), ROOST_PP_FOR_210, ROOST_PP_TUPLE_EAT_4)(o(210, s), p, o, m)
# define ROOST_PP_FOR_210_I(s, p, o, m) ROOST_PP_IF(p(211, s), m, ROOST_PP_TUPLE_EAT_2)(211, s) ROOST_PP_IF(p(211, s), ROOST_PP_FOR_211, ROOST_PP_TUPLE_EAT_4)(o(211, s), p, o, m)
# define ROOST_PP_FOR_211_I(s, p, o, m) ROOST_PP_IF(p(212, s), m, ROOST_PP_TUPLE_EAT_2)(212, s) ROOST_PP_IF(p(212, s), ROOST_PP_FOR_212, ROOST_PP_TUPLE_EAT_4)(o(212, s), p, o, m)
# define ROOST_PP_FOR_212_I(s, p, o, m) ROOST_PP_IF(p(213, s), m, ROOST_PP_TUPLE_EAT_2)(213, s) ROOST_PP_IF(p(213, s), ROOST_PP_FOR_213, ROOST_PP_TUPLE_EAT_4)(o(213, s), p, o, m)
# define ROOST_PP_FOR_213_I(s, p, o, m) ROOST_PP_IF(p(214, s), m, ROOST_PP_TUPLE_EAT_2)(214, s) ROOST_PP_IF(p(214, s), ROOST_PP_FOR_214, ROOST_PP_TUPLE_EAT_4)(o(214, s), p, o, m)
# define ROOST_PP_FOR_214_I(s, p, o, m) ROOST_PP_IF(p(215, s), m, ROOST_PP_TUPLE_EAT_2)(215, s) ROOST_PP_IF(p(215, s), ROOST_PP_FOR_215, ROOST_PP_TUPLE_EAT_4)(o(215, s), p, o, m)
# define ROOST_PP_FOR_215_I(s, p, o, m) ROOST_PP_IF(p(216, s), m, ROOST_PP_TUPLE_EAT_2)(216, s) ROOST_PP_IF(p(216, s), ROOST_PP_FOR_216, ROOST_PP_TUPLE_EAT_4)(o(216, s), p, o, m)
# define ROOST_PP_FOR_216_I(s, p, o, m) ROOST_PP_IF(p(217, s), m, ROOST_PP_TUPLE_EAT_2)(217, s) ROOST_PP_IF(p(217, s), ROOST_PP_FOR_217, ROOST_PP_TUPLE_EAT_4)(o(217, s), p, o, m)
# define ROOST_PP_FOR_217_I(s, p, o, m) ROOST_PP_IF(p(218, s), m, ROOST_PP_TUPLE_EAT_2)(218, s) ROOST_PP_IF(p(218, s), ROOST_PP_FOR_218, ROOST_PP_TUPLE_EAT_4)(o(218, s), p, o, m)
# define ROOST_PP_FOR_218_I(s, p, o, m) ROOST_PP_IF(p(219, s), m, ROOST_PP_TUPLE_EAT_2)(219, s) ROOST_PP_IF(p(219, s), ROOST_PP_FOR_219, ROOST_PP_TUPLE_EAT_4)(o(219, s), p, o, m)
# define ROOST_PP_FOR_219_I(s, p, o, m) ROOST_PP_IF(p(220, s), m, ROOST_PP_TUPLE_EAT_2)(220, s) ROOST_PP_IF(p(220, s), ROOST_PP_FOR_220, ROOST_PP_TUPLE_EAT_4)(o(220, s), p, o, m)
# define ROOST_PP_FOR_220_I(s, p, o, m) ROOST_PP_IF(p(221, s), m, ROOST_PP_TUPLE_EAT_2)(221, s) ROOST_PP_IF(p(221, s), ROOST_PP_FOR_221, ROOST_PP_TUPLE_EAT_4)(o(221, s), p, o, m)
# define ROOST_PP_FOR_221_I(s, p, o, m) ROOST_PP_IF(p(222, s), m, ROOST_PP_TUPLE_EAT_2)(222, s) ROOST_PP_IF(p(222, s), ROOST_PP_FOR_222, ROOST_PP_TUPLE_EAT_4)(o(222, s), p, o, m)
# define ROOST_PP_FOR_222_I(s, p, o, m) ROOST_PP_IF(p(223, s), m, ROOST_PP_TUPLE_EAT_2)(223, s) ROOST_PP_IF(p(223, s), ROOST_PP_FOR_223, ROOST_PP_TUPLE_EAT_4)(o(223, s), p, o, m)
# define ROOST_PP_FOR_223_I(s, p, o, m) ROOST_PP_IF(p(224, s), m, ROOST_PP_TUPLE_EAT_2)(224, s) ROOST_PP_IF(p(224, s), ROOST_PP_FOR_224, ROOST_PP_TUPLE_EAT_4)(o(224, s), p, o, m)
# define ROOST_PP_FOR_224_I(s, p, o, m) ROOST_PP_IF(p(225, s), m, ROOST_PP_TUPLE_EAT_2)(225, s) ROOST_PP_IF(p(225, s), ROOST_PP_FOR_225, ROOST_PP_TUPLE_EAT_4)(o(225, s), p, o, m)
# define ROOST_PP_FOR_225_I(s, p, o, m) ROOST_PP_IF(p(226, s), m, ROOST_PP_TUPLE_EAT_2)(226, s) ROOST_PP_IF(p(226, s), ROOST_PP_FOR_226, ROOST_PP_TUPLE_EAT_4)(o(226, s), p, o, m)
# define ROOST_PP_FOR_226_I(s, p, o, m) ROOST_PP_IF(p(227, s), m, ROOST_PP_TUPLE_EAT_2)(227, s) ROOST_PP_IF(p(227, s), ROOST_PP_FOR_227, ROOST_PP_TUPLE_EAT_4)(o(227, s), p, o, m)
# define ROOST_PP_FOR_227_I(s, p, o, m) ROOST_PP_IF(p(228, s), m, ROOST_PP_TUPLE_EAT_2)(228, s) ROOST_PP_IF(p(228, s), ROOST_PP_FOR_228, ROOST_PP_TUPLE_EAT_4)(o(228, s), p, o, m)
# define ROOST_PP_FOR_228_I(s, p, o, m) ROOST_PP_IF(p(229, s), m, ROOST_PP_TUPLE_EAT_2)(229, s) ROOST_PP_IF(p(229, s), ROOST_PP_FOR_229, ROOST_PP_TUPLE_EAT_4)(o(229, s), p, o, m)
# define ROOST_PP_FOR_229_I(s, p, o, m) ROOST_PP_IF(p(230, s), m, ROOST_PP_TUPLE_EAT_2)(230, s) ROOST_PP_IF(p(230, s), ROOST_PP_FOR_230, ROOST_PP_TUPLE_EAT_4)(o(230, s), p, o, m)
# define ROOST_PP_FOR_230_I(s, p, o, m) ROOST_PP_IF(p(231, s), m, ROOST_PP_TUPLE_EAT_2)(231, s) ROOST_PP_IF(p(231, s), ROOST_PP_FOR_231, ROOST_PP_TUPLE_EAT_4)(o(231, s), p, o, m)
# define ROOST_PP_FOR_231_I(s, p, o, m) ROOST_PP_IF(p(232, s), m, ROOST_PP_TUPLE_EAT_2)(232, s) ROOST_PP_IF(p(232, s), ROOST_PP_FOR_232, ROOST_PP_TUPLE_EAT_4)(o(232, s), p, o, m)
# define ROOST_PP_FOR_232_I(s, p, o, m) ROOST_PP_IF(p(233, s), m, ROOST_PP_TUPLE_EAT_2)(233, s) ROOST_PP_IF(p(233, s), ROOST_PP_FOR_233, ROOST_PP_TUPLE_EAT_4)(o(233, s), p, o, m)
# define ROOST_PP_FOR_233_I(s, p, o, m) ROOST_PP_IF(p(234, s), m, ROOST_PP_TUPLE_EAT_2)(234, s) ROOST_PP_IF(p(234, s), ROOST_PP_FOR_234, ROOST_PP_TUPLE_EAT_4)(o(234, s), p, o, m)
# define ROOST_PP_FOR_234_I(s, p, o, m) ROOST_PP_IF(p(235, s), m, ROOST_PP_TUPLE_EAT_2)(235, s) ROOST_PP_IF(p(235, s), ROOST_PP_FOR_235, ROOST_PP_TUPLE_EAT_4)(o(235, s), p, o, m)
# define ROOST_PP_FOR_235_I(s, p, o, m) ROOST_PP_IF(p(236, s), m, ROOST_PP_TUPLE_EAT_2)(236, s) ROOST_PP_IF(p(236, s), ROOST_PP_FOR_236, ROOST_PP_TUPLE_EAT_4)(o(236, s), p, o, m)
# define ROOST_PP_FOR_236_I(s, p, o, m) ROOST_PP_IF(p(237, s), m, ROOST_PP_TUPLE_EAT_2)(237, s) ROOST_PP_IF(p(237, s), ROOST_PP_FOR_237, ROOST_PP_TUPLE_EAT_4)(o(237, s), p, o, m)
# define ROOST_PP_FOR_237_I(s, p, o, m) ROOST_PP_IF(p(238, s), m, ROOST_PP_TUPLE_EAT_2)(238, s) ROOST_PP_IF(p(238, s), ROOST_PP_FOR_238, ROOST_PP_TUPLE_EAT_4)(o(238, s), p, o, m)
# define ROOST_PP_FOR_238_I(s, p, o, m) ROOST_PP_IF(p(239, s), m, ROOST_PP_TUPLE_EAT_2)(239, s) ROOST_PP_IF(p(239, s), ROOST_PP_FOR_239, ROOST_PP_TUPLE_EAT_4)(o(239, s), p, o, m)
# define ROOST_PP_FOR_239_I(s, p, o, m) ROOST_PP_IF(p(240, s), m, ROOST_PP_TUPLE_EAT_2)(240, s) ROOST_PP_IF(p(240, s), ROOST_PP_FOR_240, ROOST_PP_TUPLE_EAT_4)(o(240, s), p, o, m)
# define ROOST_PP_FOR_240_I(s, p, o, m) ROOST_PP_IF(p(241, s), m, ROOST_PP_TUPLE_EAT_2)(241, s) ROOST_PP_IF(p(241, s), ROOST_PP_FOR_241, ROOST_PP_TUPLE_EAT_4)(o(241, s), p, o, m)
# define ROOST_PP_FOR_241_I(s, p, o, m) ROOST_PP_IF(p(242, s), m, ROOST_PP_TUPLE_EAT_2)(242, s) ROOST_PP_IF(p(242, s), ROOST_PP_FOR_242, ROOST_PP_TUPLE_EAT_4)(o(242, s), p, o, m)
# define ROOST_PP_FOR_242_I(s, p, o, m) ROOST_PP_IF(p(243, s), m, ROOST_PP_TUPLE_EAT_2)(243, s) ROOST_PP_IF(p(243, s), ROOST_PP_FOR_243, ROOST_PP_TUPLE_EAT_4)(o(243, s), p, o, m)
# define ROOST_PP_FOR_243_I(s, p, o, m) ROOST_PP_IF(p(244, s), m, ROOST_PP_TUPLE_EAT_2)(244, s) ROOST_PP_IF(p(244, s), ROOST_PP_FOR_244, ROOST_PP_TUPLE_EAT_4)(o(244, s), p, o, m)
# define ROOST_PP_FOR_244_I(s, p, o, m) ROOST_PP_IF(p(245, s), m, ROOST_PP_TUPLE_EAT_2)(245, s) ROOST_PP_IF(p(245, s), ROOST_PP_FOR_245, ROOST_PP_TUPLE_EAT_4)(o(245, s), p, o, m)
# define ROOST_PP_FOR_245_I(s, p, o, m) ROOST_PP_IF(p(246, s), m, ROOST_PP_TUPLE_EAT_2)(246, s) ROOST_PP_IF(p(246, s), ROOST_PP_FOR_246, ROOST_PP_TUPLE_EAT_4)(o(246, s), p, o, m)
# define ROOST_PP_FOR_246_I(s, p, o, m) ROOST_PP_IF(p(247, s), m, ROOST_PP_TUPLE_EAT_2)(247, s) ROOST_PP_IF(p(247, s), ROOST_PP_FOR_247, ROOST_PP_TUPLE_EAT_4)(o(247, s), p, o, m)
# define ROOST_PP_FOR_247_I(s, p, o, m) ROOST_PP_IF(p(248, s), m, ROOST_PP_TUPLE_EAT_2)(248, s) ROOST_PP_IF(p(248, s), ROOST_PP_FOR_248, ROOST_PP_TUPLE_EAT_4)(o(248, s), p, o, m)
# define ROOST_PP_FOR_248_I(s, p, o, m) ROOST_PP_IF(p(249, s), m, ROOST_PP_TUPLE_EAT_2)(249, s) ROOST_PP_IF(p(249, s), ROOST_PP_FOR_249, ROOST_PP_TUPLE_EAT_4)(o(249, s), p, o, m)
# define ROOST_PP_FOR_249_I(s, p, o, m) ROOST_PP_IF(p(250, s), m, ROOST_PP_TUPLE_EAT_2)(250, s) ROOST_PP_IF(p(250, s), ROOST_PP_FOR_250, ROOST_PP_TUPLE_EAT_4)(o(250, s), p, o, m)
# define ROOST_PP_FOR_250_I(s, p, o, m) ROOST_PP_IF(p(251, s), m, ROOST_PP_TUPLE_EAT_2)(251, s) ROOST_PP_IF(p(251, s), ROOST_PP_FOR_251, ROOST_PP_TUPLE_EAT_4)(o(251, s), p, o, m)
# define ROOST_PP_FOR_251_I(s, p, o, m) ROOST_PP_IF(p(252, s), m, ROOST_PP_TUPLE_EAT_2)(252, s) ROOST_PP_IF(p(252, s), ROOST_PP_FOR_252, ROOST_PP_TUPLE_EAT_4)(o(252, s), p, o, m)
# define ROOST_PP_FOR_252_I(s, p, o, m) ROOST_PP_IF(p(253, s), m, ROOST_PP_TUPLE_EAT_2)(253, s) ROOST_PP_IF(p(253, s), ROOST_PP_FOR_253, ROOST_PP_TUPLE_EAT_4)(o(253, s), p, o, m)
# define ROOST_PP_FOR_253_I(s, p, o, m) ROOST_PP_IF(p(254, s), m, ROOST_PP_TUPLE_EAT_2)(254, s) ROOST_PP_IF(p(254, s), ROOST_PP_FOR_254, ROOST_PP_TUPLE_EAT_4)(o(254, s), p, o, m)
# define ROOST_PP_FOR_254_I(s, p, o, m) ROOST_PP_IF(p(255, s), m, ROOST_PP_TUPLE_EAT_2)(255, s) ROOST_PP_IF(p(255, s), ROOST_PP_FOR_255, ROOST_PP_TUPLE_EAT_4)(o(255, s), p, o, m)
# define ROOST_PP_FOR_255_I(s, p, o, m) ROOST_PP_IF(p(256, s), m, ROOST_PP_TUPLE_EAT_2)(256, s) ROOST_PP_IF(p(256, s), ROOST_PP_FOR_256, ROOST_PP_TUPLE_EAT_4)(o(256, s), p, o, m)
# define ROOST_PP_FOR_256_I(s, p, o, m) ROOST_PP_IF(p(257, s), m, ROOST_PP_TUPLE_EAT_2)(257, s) ROOST_PP_IF(p(257, s), ROOST_PP_FOR_257, ROOST_PP_TUPLE_EAT_4)(o(257, s), p, o, m)
#
# endif
