# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Roost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.roost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.roost.org for most recent version. */
#
# ifndef ROOST_PREPROCESSOR_SEQ_ELEM_HPP
# define ROOST_PREPROCESSOR_SEQ_ELEM_HPP
#
# include <roost/preprocessor/cat.hpp>
# include <roost/preprocessor/config/config.hpp>
# include <roost/preprocessor/facilities/empty.hpp>
#
# /* ROOST_PP_SEQ_ELEM */
#
# if ~ROOST_PP_CONFIG_FLAGS() & ROOST_PP_CONFIG_MWCC()
#    define ROOST_PP_SEQ_ELEM(i, seq) ROOST_PP_SEQ_ELEM_I(i, seq)
# else
#    define ROOST_PP_SEQ_ELEM(i, seq) ROOST_PP_SEQ_ELEM_I((i, seq))
# endif
#
# if ROOST_PP_CONFIG_FLAGS() & ROOST_PP_CONFIG_MSVC()
#    define ROOST_PP_SEQ_ELEM_I(i, seq) ROOST_PP_SEQ_ELEM_II((ROOST_PP_SEQ_ELEM_ ## i seq))
#    define ROOST_PP_SEQ_ELEM_II(res) ROOST_PP_SEQ_ELEM_IV(ROOST_PP_SEQ_ELEM_III res)
#    define ROOST_PP_SEQ_ELEM_III(x, _) x ROOST_PP_EMPTY()
#    define ROOST_PP_SEQ_ELEM_IV(x) x
# elif ROOST_PP_CONFIG_FLAGS() & ROOST_PP_CONFIG_MWCC()
#    define ROOST_PP_SEQ_ELEM_I(par) ROOST_PP_SEQ_ELEM_II ## par
#    define ROOST_PP_SEQ_ELEM_II(i, seq) ROOST_PP_SEQ_ELEM_III(ROOST_PP_SEQ_ELEM_ ## i ## seq)
#    define ROOST_PP_SEQ_ELEM_III(im) ROOST_PP_SEQ_ELEM_IV(im)
#    define ROOST_PP_SEQ_ELEM_IV(x, _) x
# else
#    if defined(__IBMC__) || defined(__IBMCPP__)
#        define ROOST_PP_SEQ_ELEM_I(i, seq) ROOST_PP_SEQ_ELEM_II(ROOST_PP_CAT(ROOST_PP_SEQ_ELEM_ ## i, seq))
#    else
#        define ROOST_PP_SEQ_ELEM_I(i, seq) ROOST_PP_SEQ_ELEM_II(ROOST_PP_SEQ_ELEM_ ## i seq)
#    endif
#    define ROOST_PP_SEQ_ELEM_II(im) ROOST_PP_SEQ_ELEM_III(im)
#    define ROOST_PP_SEQ_ELEM_III(x, _) x
# endif
#
# define ROOST_PP_SEQ_ELEM_0(x) x, ROOST_PP_NIL
# define ROOST_PP_SEQ_ELEM_1(_) ROOST_PP_SEQ_ELEM_0
# define ROOST_PP_SEQ_ELEM_2(_) ROOST_PP_SEQ_ELEM_1
# define ROOST_PP_SEQ_ELEM_3(_) ROOST_PP_SEQ_ELEM_2
# define ROOST_PP_SEQ_ELEM_4(_) ROOST_PP_SEQ_ELEM_3
# define ROOST_PP_SEQ_ELEM_5(_) ROOST_PP_SEQ_ELEM_4
# define ROOST_PP_SEQ_ELEM_6(_) ROOST_PP_SEQ_ELEM_5
# define ROOST_PP_SEQ_ELEM_7(_) ROOST_PP_SEQ_ELEM_6
# define ROOST_PP_SEQ_ELEM_8(_) ROOST_PP_SEQ_ELEM_7
# define ROOST_PP_SEQ_ELEM_9(_) ROOST_PP_SEQ_ELEM_8
# define ROOST_PP_SEQ_ELEM_10(_) ROOST_PP_SEQ_ELEM_9
# define ROOST_PP_SEQ_ELEM_11(_) ROOST_PP_SEQ_ELEM_10
# define ROOST_PP_SEQ_ELEM_12(_) ROOST_PP_SEQ_ELEM_11
# define ROOST_PP_SEQ_ELEM_13(_) ROOST_PP_SEQ_ELEM_12
# define ROOST_PP_SEQ_ELEM_14(_) ROOST_PP_SEQ_ELEM_13
# define ROOST_PP_SEQ_ELEM_15(_) ROOST_PP_SEQ_ELEM_14
# define ROOST_PP_SEQ_ELEM_16(_) ROOST_PP_SEQ_ELEM_15
# define ROOST_PP_SEQ_ELEM_17(_) ROOST_PP_SEQ_ELEM_16
# define ROOST_PP_SEQ_ELEM_18(_) ROOST_PP_SEQ_ELEM_17
# define ROOST_PP_SEQ_ELEM_19(_) ROOST_PP_SEQ_ELEM_18
# define ROOST_PP_SEQ_ELEM_20(_) ROOST_PP_SEQ_ELEM_19
# define ROOST_PP_SEQ_ELEM_21(_) ROOST_PP_SEQ_ELEM_20
# define ROOST_PP_SEQ_ELEM_22(_) ROOST_PP_SEQ_ELEM_21
# define ROOST_PP_SEQ_ELEM_23(_) ROOST_PP_SEQ_ELEM_22
# define ROOST_PP_SEQ_ELEM_24(_) ROOST_PP_SEQ_ELEM_23
# define ROOST_PP_SEQ_ELEM_25(_) ROOST_PP_SEQ_ELEM_24
# define ROOST_PP_SEQ_ELEM_26(_) ROOST_PP_SEQ_ELEM_25
# define ROOST_PP_SEQ_ELEM_27(_) ROOST_PP_SEQ_ELEM_26
# define ROOST_PP_SEQ_ELEM_28(_) ROOST_PP_SEQ_ELEM_27
# define ROOST_PP_SEQ_ELEM_29(_) ROOST_PP_SEQ_ELEM_28
# define ROOST_PP_SEQ_ELEM_30(_) ROOST_PP_SEQ_ELEM_29
# define ROOST_PP_SEQ_ELEM_31(_) ROOST_PP_SEQ_ELEM_30
# define ROOST_PP_SEQ_ELEM_32(_) ROOST_PP_SEQ_ELEM_31
# define ROOST_PP_SEQ_ELEM_33(_) ROOST_PP_SEQ_ELEM_32
# define ROOST_PP_SEQ_ELEM_34(_) ROOST_PP_SEQ_ELEM_33
# define ROOST_PP_SEQ_ELEM_35(_) ROOST_PP_SEQ_ELEM_34
# define ROOST_PP_SEQ_ELEM_36(_) ROOST_PP_SEQ_ELEM_35
# define ROOST_PP_SEQ_ELEM_37(_) ROOST_PP_SEQ_ELEM_36
# define ROOST_PP_SEQ_ELEM_38(_) ROOST_PP_SEQ_ELEM_37
# define ROOST_PP_SEQ_ELEM_39(_) ROOST_PP_SEQ_ELEM_38
# define ROOST_PP_SEQ_ELEM_40(_) ROOST_PP_SEQ_ELEM_39
# define ROOST_PP_SEQ_ELEM_41(_) ROOST_PP_SEQ_ELEM_40
# define ROOST_PP_SEQ_ELEM_42(_) ROOST_PP_SEQ_ELEM_41
# define ROOST_PP_SEQ_ELEM_43(_) ROOST_PP_SEQ_ELEM_42
# define ROOST_PP_SEQ_ELEM_44(_) ROOST_PP_SEQ_ELEM_43
# define ROOST_PP_SEQ_ELEM_45(_) ROOST_PP_SEQ_ELEM_44
# define ROOST_PP_SEQ_ELEM_46(_) ROOST_PP_SEQ_ELEM_45
# define ROOST_PP_SEQ_ELEM_47(_) ROOST_PP_SEQ_ELEM_46
# define ROOST_PP_SEQ_ELEM_48(_) ROOST_PP_SEQ_ELEM_47
# define ROOST_PP_SEQ_ELEM_49(_) ROOST_PP_SEQ_ELEM_48
# define ROOST_PP_SEQ_ELEM_50(_) ROOST_PP_SEQ_ELEM_49
# define ROOST_PP_SEQ_ELEM_51(_) ROOST_PP_SEQ_ELEM_50
# define ROOST_PP_SEQ_ELEM_52(_) ROOST_PP_SEQ_ELEM_51
# define ROOST_PP_SEQ_ELEM_53(_) ROOST_PP_SEQ_ELEM_52
# define ROOST_PP_SEQ_ELEM_54(_) ROOST_PP_SEQ_ELEM_53
# define ROOST_PP_SEQ_ELEM_55(_) ROOST_PP_SEQ_ELEM_54
# define ROOST_PP_SEQ_ELEM_56(_) ROOST_PP_SEQ_ELEM_55
# define ROOST_PP_SEQ_ELEM_57(_) ROOST_PP_SEQ_ELEM_56
# define ROOST_PP_SEQ_ELEM_58(_) ROOST_PP_SEQ_ELEM_57
# define ROOST_PP_SEQ_ELEM_59(_) ROOST_PP_SEQ_ELEM_58
# define ROOST_PP_SEQ_ELEM_60(_) ROOST_PP_SEQ_ELEM_59
# define ROOST_PP_SEQ_ELEM_61(_) ROOST_PP_SEQ_ELEM_60
# define ROOST_PP_SEQ_ELEM_62(_) ROOST_PP_SEQ_ELEM_61
# define ROOST_PP_SEQ_ELEM_63(_) ROOST_PP_SEQ_ELEM_62
# define ROOST_PP_SEQ_ELEM_64(_) ROOST_PP_SEQ_ELEM_63
# define ROOST_PP_SEQ_ELEM_65(_) ROOST_PP_SEQ_ELEM_64
# define ROOST_PP_SEQ_ELEM_66(_) ROOST_PP_SEQ_ELEM_65
# define ROOST_PP_SEQ_ELEM_67(_) ROOST_PP_SEQ_ELEM_66
# define ROOST_PP_SEQ_ELEM_68(_) ROOST_PP_SEQ_ELEM_67
# define ROOST_PP_SEQ_ELEM_69(_) ROOST_PP_SEQ_ELEM_68
# define ROOST_PP_SEQ_ELEM_70(_) ROOST_PP_SEQ_ELEM_69
# define ROOST_PP_SEQ_ELEM_71(_) ROOST_PP_SEQ_ELEM_70
# define ROOST_PP_SEQ_ELEM_72(_) ROOST_PP_SEQ_ELEM_71
# define ROOST_PP_SEQ_ELEM_73(_) ROOST_PP_SEQ_ELEM_72
# define ROOST_PP_SEQ_ELEM_74(_) ROOST_PP_SEQ_ELEM_73
# define ROOST_PP_SEQ_ELEM_75(_) ROOST_PP_SEQ_ELEM_74
# define ROOST_PP_SEQ_ELEM_76(_) ROOST_PP_SEQ_ELEM_75
# define ROOST_PP_SEQ_ELEM_77(_) ROOST_PP_SEQ_ELEM_76
# define ROOST_PP_SEQ_ELEM_78(_) ROOST_PP_SEQ_ELEM_77
# define ROOST_PP_SEQ_ELEM_79(_) ROOST_PP_SEQ_ELEM_78
# define ROOST_PP_SEQ_ELEM_80(_) ROOST_PP_SEQ_ELEM_79
# define ROOST_PP_SEQ_ELEM_81(_) ROOST_PP_SEQ_ELEM_80
# define ROOST_PP_SEQ_ELEM_82(_) ROOST_PP_SEQ_ELEM_81
# define ROOST_PP_SEQ_ELEM_83(_) ROOST_PP_SEQ_ELEM_82
# define ROOST_PP_SEQ_ELEM_84(_) ROOST_PP_SEQ_ELEM_83
# define ROOST_PP_SEQ_ELEM_85(_) ROOST_PP_SEQ_ELEM_84
# define ROOST_PP_SEQ_ELEM_86(_) ROOST_PP_SEQ_ELEM_85
# define ROOST_PP_SEQ_ELEM_87(_) ROOST_PP_SEQ_ELEM_86
# define ROOST_PP_SEQ_ELEM_88(_) ROOST_PP_SEQ_ELEM_87
# define ROOST_PP_SEQ_ELEM_89(_) ROOST_PP_SEQ_ELEM_88
# define ROOST_PP_SEQ_ELEM_90(_) ROOST_PP_SEQ_ELEM_89
# define ROOST_PP_SEQ_ELEM_91(_) ROOST_PP_SEQ_ELEM_90
# define ROOST_PP_SEQ_ELEM_92(_) ROOST_PP_SEQ_ELEM_91
# define ROOST_PP_SEQ_ELEM_93(_) ROOST_PP_SEQ_ELEM_92
# define ROOST_PP_SEQ_ELEM_94(_) ROOST_PP_SEQ_ELEM_93
# define ROOST_PP_SEQ_ELEM_95(_) ROOST_PP_SEQ_ELEM_94
# define ROOST_PP_SEQ_ELEM_96(_) ROOST_PP_SEQ_ELEM_95
# define ROOST_PP_SEQ_ELEM_97(_) ROOST_PP_SEQ_ELEM_96
# define ROOST_PP_SEQ_ELEM_98(_) ROOST_PP_SEQ_ELEM_97
# define ROOST_PP_SEQ_ELEM_99(_) ROOST_PP_SEQ_ELEM_98
# define ROOST_PP_SEQ_ELEM_100(_) ROOST_PP_SEQ_ELEM_99
# define ROOST_PP_SEQ_ELEM_101(_) ROOST_PP_SEQ_ELEM_100
# define ROOST_PP_SEQ_ELEM_102(_) ROOST_PP_SEQ_ELEM_101
# define ROOST_PP_SEQ_ELEM_103(_) ROOST_PP_SEQ_ELEM_102
# define ROOST_PP_SEQ_ELEM_104(_) ROOST_PP_SEQ_ELEM_103
# define ROOST_PP_SEQ_ELEM_105(_) ROOST_PP_SEQ_ELEM_104
# define ROOST_PP_SEQ_ELEM_106(_) ROOST_PP_SEQ_ELEM_105
# define ROOST_PP_SEQ_ELEM_107(_) ROOST_PP_SEQ_ELEM_106
# define ROOST_PP_SEQ_ELEM_108(_) ROOST_PP_SEQ_ELEM_107
# define ROOST_PP_SEQ_ELEM_109(_) ROOST_PP_SEQ_ELEM_108
# define ROOST_PP_SEQ_ELEM_110(_) ROOST_PP_SEQ_ELEM_109
# define ROOST_PP_SEQ_ELEM_111(_) ROOST_PP_SEQ_ELEM_110
# define ROOST_PP_SEQ_ELEM_112(_) ROOST_PP_SEQ_ELEM_111
# define ROOST_PP_SEQ_ELEM_113(_) ROOST_PP_SEQ_ELEM_112
# define ROOST_PP_SEQ_ELEM_114(_) ROOST_PP_SEQ_ELEM_113
# define ROOST_PP_SEQ_ELEM_115(_) ROOST_PP_SEQ_ELEM_114
# define ROOST_PP_SEQ_ELEM_116(_) ROOST_PP_SEQ_ELEM_115
# define ROOST_PP_SEQ_ELEM_117(_) ROOST_PP_SEQ_ELEM_116
# define ROOST_PP_SEQ_ELEM_118(_) ROOST_PP_SEQ_ELEM_117
# define ROOST_PP_SEQ_ELEM_119(_) ROOST_PP_SEQ_ELEM_118
# define ROOST_PP_SEQ_ELEM_120(_) ROOST_PP_SEQ_ELEM_119
# define ROOST_PP_SEQ_ELEM_121(_) ROOST_PP_SEQ_ELEM_120
# define ROOST_PP_SEQ_ELEM_122(_) ROOST_PP_SEQ_ELEM_121
# define ROOST_PP_SEQ_ELEM_123(_) ROOST_PP_SEQ_ELEM_122
# define ROOST_PP_SEQ_ELEM_124(_) ROOST_PP_SEQ_ELEM_123
# define ROOST_PP_SEQ_ELEM_125(_) ROOST_PP_SEQ_ELEM_124
# define ROOST_PP_SEQ_ELEM_126(_) ROOST_PP_SEQ_ELEM_125
# define ROOST_PP_SEQ_ELEM_127(_) ROOST_PP_SEQ_ELEM_126
# define ROOST_PP_SEQ_ELEM_128(_) ROOST_PP_SEQ_ELEM_127
# define ROOST_PP_SEQ_ELEM_129(_) ROOST_PP_SEQ_ELEM_128
# define ROOST_PP_SEQ_ELEM_130(_) ROOST_PP_SEQ_ELEM_129
# define ROOST_PP_SEQ_ELEM_131(_) ROOST_PP_SEQ_ELEM_130
# define ROOST_PP_SEQ_ELEM_132(_) ROOST_PP_SEQ_ELEM_131
# define ROOST_PP_SEQ_ELEM_133(_) ROOST_PP_SEQ_ELEM_132
# define ROOST_PP_SEQ_ELEM_134(_) ROOST_PP_SEQ_ELEM_133
# define ROOST_PP_SEQ_ELEM_135(_) ROOST_PP_SEQ_ELEM_134
# define ROOST_PP_SEQ_ELEM_136(_) ROOST_PP_SEQ_ELEM_135
# define ROOST_PP_SEQ_ELEM_137(_) ROOST_PP_SEQ_ELEM_136
# define ROOST_PP_SEQ_ELEM_138(_) ROOST_PP_SEQ_ELEM_137
# define ROOST_PP_SEQ_ELEM_139(_) ROOST_PP_SEQ_ELEM_138
# define ROOST_PP_SEQ_ELEM_140(_) ROOST_PP_SEQ_ELEM_139
# define ROOST_PP_SEQ_ELEM_141(_) ROOST_PP_SEQ_ELEM_140
# define ROOST_PP_SEQ_ELEM_142(_) ROOST_PP_SEQ_ELEM_141
# define ROOST_PP_SEQ_ELEM_143(_) ROOST_PP_SEQ_ELEM_142
# define ROOST_PP_SEQ_ELEM_144(_) ROOST_PP_SEQ_ELEM_143
# define ROOST_PP_SEQ_ELEM_145(_) ROOST_PP_SEQ_ELEM_144
# define ROOST_PP_SEQ_ELEM_146(_) ROOST_PP_SEQ_ELEM_145
# define ROOST_PP_SEQ_ELEM_147(_) ROOST_PP_SEQ_ELEM_146
# define ROOST_PP_SEQ_ELEM_148(_) ROOST_PP_SEQ_ELEM_147
# define ROOST_PP_SEQ_ELEM_149(_) ROOST_PP_SEQ_ELEM_148
# define ROOST_PP_SEQ_ELEM_150(_) ROOST_PP_SEQ_ELEM_149
# define ROOST_PP_SEQ_ELEM_151(_) ROOST_PP_SEQ_ELEM_150
# define ROOST_PP_SEQ_ELEM_152(_) ROOST_PP_SEQ_ELEM_151
# define ROOST_PP_SEQ_ELEM_153(_) ROOST_PP_SEQ_ELEM_152
# define ROOST_PP_SEQ_ELEM_154(_) ROOST_PP_SEQ_ELEM_153
# define ROOST_PP_SEQ_ELEM_155(_) ROOST_PP_SEQ_ELEM_154
# define ROOST_PP_SEQ_ELEM_156(_) ROOST_PP_SEQ_ELEM_155
# define ROOST_PP_SEQ_ELEM_157(_) ROOST_PP_SEQ_ELEM_156
# define ROOST_PP_SEQ_ELEM_158(_) ROOST_PP_SEQ_ELEM_157
# define ROOST_PP_SEQ_ELEM_159(_) ROOST_PP_SEQ_ELEM_158
# define ROOST_PP_SEQ_ELEM_160(_) ROOST_PP_SEQ_ELEM_159
# define ROOST_PP_SEQ_ELEM_161(_) ROOST_PP_SEQ_ELEM_160
# define ROOST_PP_SEQ_ELEM_162(_) ROOST_PP_SEQ_ELEM_161
# define ROOST_PP_SEQ_ELEM_163(_) ROOST_PP_SEQ_ELEM_162
# define ROOST_PP_SEQ_ELEM_164(_) ROOST_PP_SEQ_ELEM_163
# define ROOST_PP_SEQ_ELEM_165(_) ROOST_PP_SEQ_ELEM_164
# define ROOST_PP_SEQ_ELEM_166(_) ROOST_PP_SEQ_ELEM_165
# define ROOST_PP_SEQ_ELEM_167(_) ROOST_PP_SEQ_ELEM_166
# define ROOST_PP_SEQ_ELEM_168(_) ROOST_PP_SEQ_ELEM_167
# define ROOST_PP_SEQ_ELEM_169(_) ROOST_PP_SEQ_ELEM_168
# define ROOST_PP_SEQ_ELEM_170(_) ROOST_PP_SEQ_ELEM_169
# define ROOST_PP_SEQ_ELEM_171(_) ROOST_PP_SEQ_ELEM_170
# define ROOST_PP_SEQ_ELEM_172(_) ROOST_PP_SEQ_ELEM_171
# define ROOST_PP_SEQ_ELEM_173(_) ROOST_PP_SEQ_ELEM_172
# define ROOST_PP_SEQ_ELEM_174(_) ROOST_PP_SEQ_ELEM_173
# define ROOST_PP_SEQ_ELEM_175(_) ROOST_PP_SEQ_ELEM_174
# define ROOST_PP_SEQ_ELEM_176(_) ROOST_PP_SEQ_ELEM_175
# define ROOST_PP_SEQ_ELEM_177(_) ROOST_PP_SEQ_ELEM_176
# define ROOST_PP_SEQ_ELEM_178(_) ROOST_PP_SEQ_ELEM_177
# define ROOST_PP_SEQ_ELEM_179(_) ROOST_PP_SEQ_ELEM_178
# define ROOST_PP_SEQ_ELEM_180(_) ROOST_PP_SEQ_ELEM_179
# define ROOST_PP_SEQ_ELEM_181(_) ROOST_PP_SEQ_ELEM_180
# define ROOST_PP_SEQ_ELEM_182(_) ROOST_PP_SEQ_ELEM_181
# define ROOST_PP_SEQ_ELEM_183(_) ROOST_PP_SEQ_ELEM_182
# define ROOST_PP_SEQ_ELEM_184(_) ROOST_PP_SEQ_ELEM_183
# define ROOST_PP_SEQ_ELEM_185(_) ROOST_PP_SEQ_ELEM_184
# define ROOST_PP_SEQ_ELEM_186(_) ROOST_PP_SEQ_ELEM_185
# define ROOST_PP_SEQ_ELEM_187(_) ROOST_PP_SEQ_ELEM_186
# define ROOST_PP_SEQ_ELEM_188(_) ROOST_PP_SEQ_ELEM_187
# define ROOST_PP_SEQ_ELEM_189(_) ROOST_PP_SEQ_ELEM_188
# define ROOST_PP_SEQ_ELEM_190(_) ROOST_PP_SEQ_ELEM_189
# define ROOST_PP_SEQ_ELEM_191(_) ROOST_PP_SEQ_ELEM_190
# define ROOST_PP_SEQ_ELEM_192(_) ROOST_PP_SEQ_ELEM_191
# define ROOST_PP_SEQ_ELEM_193(_) ROOST_PP_SEQ_ELEM_192
# define ROOST_PP_SEQ_ELEM_194(_) ROOST_PP_SEQ_ELEM_193
# define ROOST_PP_SEQ_ELEM_195(_) ROOST_PP_SEQ_ELEM_194
# define ROOST_PP_SEQ_ELEM_196(_) ROOST_PP_SEQ_ELEM_195
# define ROOST_PP_SEQ_ELEM_197(_) ROOST_PP_SEQ_ELEM_196
# define ROOST_PP_SEQ_ELEM_198(_) ROOST_PP_SEQ_ELEM_197
# define ROOST_PP_SEQ_ELEM_199(_) ROOST_PP_SEQ_ELEM_198
# define ROOST_PP_SEQ_ELEM_200(_) ROOST_PP_SEQ_ELEM_199
# define ROOST_PP_SEQ_ELEM_201(_) ROOST_PP_SEQ_ELEM_200
# define ROOST_PP_SEQ_ELEM_202(_) ROOST_PP_SEQ_ELEM_201
# define ROOST_PP_SEQ_ELEM_203(_) ROOST_PP_SEQ_ELEM_202
# define ROOST_PP_SEQ_ELEM_204(_) ROOST_PP_SEQ_ELEM_203
# define ROOST_PP_SEQ_ELEM_205(_) ROOST_PP_SEQ_ELEM_204
# define ROOST_PP_SEQ_ELEM_206(_) ROOST_PP_SEQ_ELEM_205
# define ROOST_PP_SEQ_ELEM_207(_) ROOST_PP_SEQ_ELEM_206
# define ROOST_PP_SEQ_ELEM_208(_) ROOST_PP_SEQ_ELEM_207
# define ROOST_PP_SEQ_ELEM_209(_) ROOST_PP_SEQ_ELEM_208
# define ROOST_PP_SEQ_ELEM_210(_) ROOST_PP_SEQ_ELEM_209
# define ROOST_PP_SEQ_ELEM_211(_) ROOST_PP_SEQ_ELEM_210
# define ROOST_PP_SEQ_ELEM_212(_) ROOST_PP_SEQ_ELEM_211
# define ROOST_PP_SEQ_ELEM_213(_) ROOST_PP_SEQ_ELEM_212
# define ROOST_PP_SEQ_ELEM_214(_) ROOST_PP_SEQ_ELEM_213
# define ROOST_PP_SEQ_ELEM_215(_) ROOST_PP_SEQ_ELEM_214
# define ROOST_PP_SEQ_ELEM_216(_) ROOST_PP_SEQ_ELEM_215
# define ROOST_PP_SEQ_ELEM_217(_) ROOST_PP_SEQ_ELEM_216
# define ROOST_PP_SEQ_ELEM_218(_) ROOST_PP_SEQ_ELEM_217
# define ROOST_PP_SEQ_ELEM_219(_) ROOST_PP_SEQ_ELEM_218
# define ROOST_PP_SEQ_ELEM_220(_) ROOST_PP_SEQ_ELEM_219
# define ROOST_PP_SEQ_ELEM_221(_) ROOST_PP_SEQ_ELEM_220
# define ROOST_PP_SEQ_ELEM_222(_) ROOST_PP_SEQ_ELEM_221
# define ROOST_PP_SEQ_ELEM_223(_) ROOST_PP_SEQ_ELEM_222
# define ROOST_PP_SEQ_ELEM_224(_) ROOST_PP_SEQ_ELEM_223
# define ROOST_PP_SEQ_ELEM_225(_) ROOST_PP_SEQ_ELEM_224
# define ROOST_PP_SEQ_ELEM_226(_) ROOST_PP_SEQ_ELEM_225
# define ROOST_PP_SEQ_ELEM_227(_) ROOST_PP_SEQ_ELEM_226
# define ROOST_PP_SEQ_ELEM_228(_) ROOST_PP_SEQ_ELEM_227
# define ROOST_PP_SEQ_ELEM_229(_) ROOST_PP_SEQ_ELEM_228
# define ROOST_PP_SEQ_ELEM_230(_) ROOST_PP_SEQ_ELEM_229
# define ROOST_PP_SEQ_ELEM_231(_) ROOST_PP_SEQ_ELEM_230
# define ROOST_PP_SEQ_ELEM_232(_) ROOST_PP_SEQ_ELEM_231
# define ROOST_PP_SEQ_ELEM_233(_) ROOST_PP_SEQ_ELEM_232
# define ROOST_PP_SEQ_ELEM_234(_) ROOST_PP_SEQ_ELEM_233
# define ROOST_PP_SEQ_ELEM_235(_) ROOST_PP_SEQ_ELEM_234
# define ROOST_PP_SEQ_ELEM_236(_) ROOST_PP_SEQ_ELEM_235
# define ROOST_PP_SEQ_ELEM_237(_) ROOST_PP_SEQ_ELEM_236
# define ROOST_PP_SEQ_ELEM_238(_) ROOST_PP_SEQ_ELEM_237
# define ROOST_PP_SEQ_ELEM_239(_) ROOST_PP_SEQ_ELEM_238
# define ROOST_PP_SEQ_ELEM_240(_) ROOST_PP_SEQ_ELEM_239
# define ROOST_PP_SEQ_ELEM_241(_) ROOST_PP_SEQ_ELEM_240
# define ROOST_PP_SEQ_ELEM_242(_) ROOST_PP_SEQ_ELEM_241
# define ROOST_PP_SEQ_ELEM_243(_) ROOST_PP_SEQ_ELEM_242
# define ROOST_PP_SEQ_ELEM_244(_) ROOST_PP_SEQ_ELEM_243
# define ROOST_PP_SEQ_ELEM_245(_) ROOST_PP_SEQ_ELEM_244
# define ROOST_PP_SEQ_ELEM_246(_) ROOST_PP_SEQ_ELEM_245
# define ROOST_PP_SEQ_ELEM_247(_) ROOST_PP_SEQ_ELEM_246
# define ROOST_PP_SEQ_ELEM_248(_) ROOST_PP_SEQ_ELEM_247
# define ROOST_PP_SEQ_ELEM_249(_) ROOST_PP_SEQ_ELEM_248
# define ROOST_PP_SEQ_ELEM_250(_) ROOST_PP_SEQ_ELEM_249
# define ROOST_PP_SEQ_ELEM_251(_) ROOST_PP_SEQ_ELEM_250
# define ROOST_PP_SEQ_ELEM_252(_) ROOST_PP_SEQ_ELEM_251
# define ROOST_PP_SEQ_ELEM_253(_) ROOST_PP_SEQ_ELEM_252
# define ROOST_PP_SEQ_ELEM_254(_) ROOST_PP_SEQ_ELEM_253
# define ROOST_PP_SEQ_ELEM_255(_) ROOST_PP_SEQ_ELEM_254
#
# endif
