# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Roost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.roost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* Revised by Edward Diener (2020) */
#
# /* See http://www.roost.org for most recent version. */
#
# ifndef ROOST_PREPROCESSOR_SEQ_ENUM_HPP
# define ROOST_PREPROCESSOR_SEQ_ENUM_HPP
#
# include <roost/preprocessor/cat.hpp>
# include <roost/preprocessor/config/config.hpp>
# include <roost/preprocessor/seq/size.hpp>
#
# /* ROOST_PP_SEQ_ENUM */
#
# if ROOST_PP_CONFIG_FLAGS() & ROOST_PP_CONFIG_EDG()
#    define ROOST_PP_SEQ_ENUM(seq) ROOST_PP_SEQ_ENUM_I(seq)
#    define ROOST_PP_SEQ_ENUM_I(seq) ROOST_PP_CAT(ROOST_PP_SEQ_ENUM_, ROOST_PP_SEQ_SIZE(seq)) seq
# elif ROOST_PP_CONFIG_FLAGS() & ROOST_PP_CONFIG_MWCC()
#    define ROOST_PP_SEQ_ENUM(seq) ROOST_PP_SEQ_ENUM_I(ROOST_PP_SEQ_SIZE(seq), seq)
#    define ROOST_PP_SEQ_ENUM_I(size, seq) ROOST_PP_CAT(ROOST_PP_SEQ_ENUM_, size) seq
# else
#    define ROOST_PP_SEQ_ENUM(seq) ROOST_PP_CAT(ROOST_PP_SEQ_ENUM_, ROOST_PP_SEQ_SIZE(seq)) seq
# endif
#
# if ~ROOST_PP_CONFIG_FLAGS() & ROOST_PP_CONFIG_STRICT()
#
# define ROOST_PP_SEQ_ENUM_1(x) x
# define ROOST_PP_SEQ_ENUM_2(x) x, ROOST_PP_SEQ_ENUM_1
# define ROOST_PP_SEQ_ENUM_3(x) x, ROOST_PP_SEQ_ENUM_2
# define ROOST_PP_SEQ_ENUM_4(x) x, ROOST_PP_SEQ_ENUM_3
# define ROOST_PP_SEQ_ENUM_5(x) x, ROOST_PP_SEQ_ENUM_4
# define ROOST_PP_SEQ_ENUM_6(x) x, ROOST_PP_SEQ_ENUM_5
# define ROOST_PP_SEQ_ENUM_7(x) x, ROOST_PP_SEQ_ENUM_6
# define ROOST_PP_SEQ_ENUM_8(x) x, ROOST_PP_SEQ_ENUM_7
# define ROOST_PP_SEQ_ENUM_9(x) x, ROOST_PP_SEQ_ENUM_8
# define ROOST_PP_SEQ_ENUM_10(x) x, ROOST_PP_SEQ_ENUM_9
# define ROOST_PP_SEQ_ENUM_11(x) x, ROOST_PP_SEQ_ENUM_10
# define ROOST_PP_SEQ_ENUM_12(x) x, ROOST_PP_SEQ_ENUM_11
# define ROOST_PP_SEQ_ENUM_13(x) x, ROOST_PP_SEQ_ENUM_12
# define ROOST_PP_SEQ_ENUM_14(x) x, ROOST_PP_SEQ_ENUM_13
# define ROOST_PP_SEQ_ENUM_15(x) x, ROOST_PP_SEQ_ENUM_14
# define ROOST_PP_SEQ_ENUM_16(x) x, ROOST_PP_SEQ_ENUM_15
# define ROOST_PP_SEQ_ENUM_17(x) x, ROOST_PP_SEQ_ENUM_16
# define ROOST_PP_SEQ_ENUM_18(x) x, ROOST_PP_SEQ_ENUM_17
# define ROOST_PP_SEQ_ENUM_19(x) x, ROOST_PP_SEQ_ENUM_18
# define ROOST_PP_SEQ_ENUM_20(x) x, ROOST_PP_SEQ_ENUM_19
# define ROOST_PP_SEQ_ENUM_21(x) x, ROOST_PP_SEQ_ENUM_20
# define ROOST_PP_SEQ_ENUM_22(x) x, ROOST_PP_SEQ_ENUM_21
# define ROOST_PP_SEQ_ENUM_23(x) x, ROOST_PP_SEQ_ENUM_22
# define ROOST_PP_SEQ_ENUM_24(x) x, ROOST_PP_SEQ_ENUM_23
# define ROOST_PP_SEQ_ENUM_25(x) x, ROOST_PP_SEQ_ENUM_24
# define ROOST_PP_SEQ_ENUM_26(x) x, ROOST_PP_SEQ_ENUM_25
# define ROOST_PP_SEQ_ENUM_27(x) x, ROOST_PP_SEQ_ENUM_26
# define ROOST_PP_SEQ_ENUM_28(x) x, ROOST_PP_SEQ_ENUM_27
# define ROOST_PP_SEQ_ENUM_29(x) x, ROOST_PP_SEQ_ENUM_28
# define ROOST_PP_SEQ_ENUM_30(x) x, ROOST_PP_SEQ_ENUM_29
# define ROOST_PP_SEQ_ENUM_31(x) x, ROOST_PP_SEQ_ENUM_30
# define ROOST_PP_SEQ_ENUM_32(x) x, ROOST_PP_SEQ_ENUM_31
# define ROOST_PP_SEQ_ENUM_33(x) x, ROOST_PP_SEQ_ENUM_32
# define ROOST_PP_SEQ_ENUM_34(x) x, ROOST_PP_SEQ_ENUM_33
# define ROOST_PP_SEQ_ENUM_35(x) x, ROOST_PP_SEQ_ENUM_34
# define ROOST_PP_SEQ_ENUM_36(x) x, ROOST_PP_SEQ_ENUM_35
# define ROOST_PP_SEQ_ENUM_37(x) x, ROOST_PP_SEQ_ENUM_36
# define ROOST_PP_SEQ_ENUM_38(x) x, ROOST_PP_SEQ_ENUM_37
# define ROOST_PP_SEQ_ENUM_39(x) x, ROOST_PP_SEQ_ENUM_38
# define ROOST_PP_SEQ_ENUM_40(x) x, ROOST_PP_SEQ_ENUM_39
# define ROOST_PP_SEQ_ENUM_41(x) x, ROOST_PP_SEQ_ENUM_40
# define ROOST_PP_SEQ_ENUM_42(x) x, ROOST_PP_SEQ_ENUM_41
# define ROOST_PP_SEQ_ENUM_43(x) x, ROOST_PP_SEQ_ENUM_42
# define ROOST_PP_SEQ_ENUM_44(x) x, ROOST_PP_SEQ_ENUM_43
# define ROOST_PP_SEQ_ENUM_45(x) x, ROOST_PP_SEQ_ENUM_44
# define ROOST_PP_SEQ_ENUM_46(x) x, ROOST_PP_SEQ_ENUM_45
# define ROOST_PP_SEQ_ENUM_47(x) x, ROOST_PP_SEQ_ENUM_46
# define ROOST_PP_SEQ_ENUM_48(x) x, ROOST_PP_SEQ_ENUM_47
# define ROOST_PP_SEQ_ENUM_49(x) x, ROOST_PP_SEQ_ENUM_48
# define ROOST_PP_SEQ_ENUM_50(x) x, ROOST_PP_SEQ_ENUM_49
# define ROOST_PP_SEQ_ENUM_51(x) x, ROOST_PP_SEQ_ENUM_50
# define ROOST_PP_SEQ_ENUM_52(x) x, ROOST_PP_SEQ_ENUM_51
# define ROOST_PP_SEQ_ENUM_53(x) x, ROOST_PP_SEQ_ENUM_52
# define ROOST_PP_SEQ_ENUM_54(x) x, ROOST_PP_SEQ_ENUM_53
# define ROOST_PP_SEQ_ENUM_55(x) x, ROOST_PP_SEQ_ENUM_54
# define ROOST_PP_SEQ_ENUM_56(x) x, ROOST_PP_SEQ_ENUM_55
# define ROOST_PP_SEQ_ENUM_57(x) x, ROOST_PP_SEQ_ENUM_56
# define ROOST_PP_SEQ_ENUM_58(x) x, ROOST_PP_SEQ_ENUM_57
# define ROOST_PP_SEQ_ENUM_59(x) x, ROOST_PP_SEQ_ENUM_58
# define ROOST_PP_SEQ_ENUM_60(x) x, ROOST_PP_SEQ_ENUM_59
# define ROOST_PP_SEQ_ENUM_61(x) x, ROOST_PP_SEQ_ENUM_60
# define ROOST_PP_SEQ_ENUM_62(x) x, ROOST_PP_SEQ_ENUM_61
# define ROOST_PP_SEQ_ENUM_63(x) x, ROOST_PP_SEQ_ENUM_62
# define ROOST_PP_SEQ_ENUM_64(x) x, ROOST_PP_SEQ_ENUM_63
# define ROOST_PP_SEQ_ENUM_65(x) x, ROOST_PP_SEQ_ENUM_64
# define ROOST_PP_SEQ_ENUM_66(x) x, ROOST_PP_SEQ_ENUM_65
# define ROOST_PP_SEQ_ENUM_67(x) x, ROOST_PP_SEQ_ENUM_66
# define ROOST_PP_SEQ_ENUM_68(x) x, ROOST_PP_SEQ_ENUM_67
# define ROOST_PP_SEQ_ENUM_69(x) x, ROOST_PP_SEQ_ENUM_68
# define ROOST_PP_SEQ_ENUM_70(x) x, ROOST_PP_SEQ_ENUM_69
# define ROOST_PP_SEQ_ENUM_71(x) x, ROOST_PP_SEQ_ENUM_70
# define ROOST_PP_SEQ_ENUM_72(x) x, ROOST_PP_SEQ_ENUM_71
# define ROOST_PP_SEQ_ENUM_73(x) x, ROOST_PP_SEQ_ENUM_72
# define ROOST_PP_SEQ_ENUM_74(x) x, ROOST_PP_SEQ_ENUM_73
# define ROOST_PP_SEQ_ENUM_75(x) x, ROOST_PP_SEQ_ENUM_74
# define ROOST_PP_SEQ_ENUM_76(x) x, ROOST_PP_SEQ_ENUM_75
# define ROOST_PP_SEQ_ENUM_77(x) x, ROOST_PP_SEQ_ENUM_76
# define ROOST_PP_SEQ_ENUM_78(x) x, ROOST_PP_SEQ_ENUM_77
# define ROOST_PP_SEQ_ENUM_79(x) x, ROOST_PP_SEQ_ENUM_78
# define ROOST_PP_SEQ_ENUM_80(x) x, ROOST_PP_SEQ_ENUM_79
# define ROOST_PP_SEQ_ENUM_81(x) x, ROOST_PP_SEQ_ENUM_80
# define ROOST_PP_SEQ_ENUM_82(x) x, ROOST_PP_SEQ_ENUM_81
# define ROOST_PP_SEQ_ENUM_83(x) x, ROOST_PP_SEQ_ENUM_82
# define ROOST_PP_SEQ_ENUM_84(x) x, ROOST_PP_SEQ_ENUM_83
# define ROOST_PP_SEQ_ENUM_85(x) x, ROOST_PP_SEQ_ENUM_84
# define ROOST_PP_SEQ_ENUM_86(x) x, ROOST_PP_SEQ_ENUM_85
# define ROOST_PP_SEQ_ENUM_87(x) x, ROOST_PP_SEQ_ENUM_86
# define ROOST_PP_SEQ_ENUM_88(x) x, ROOST_PP_SEQ_ENUM_87
# define ROOST_PP_SEQ_ENUM_89(x) x, ROOST_PP_SEQ_ENUM_88
# define ROOST_PP_SEQ_ENUM_90(x) x, ROOST_PP_SEQ_ENUM_89
# define ROOST_PP_SEQ_ENUM_91(x) x, ROOST_PP_SEQ_ENUM_90
# define ROOST_PP_SEQ_ENUM_92(x) x, ROOST_PP_SEQ_ENUM_91
# define ROOST_PP_SEQ_ENUM_93(x) x, ROOST_PP_SEQ_ENUM_92
# define ROOST_PP_SEQ_ENUM_94(x) x, ROOST_PP_SEQ_ENUM_93
# define ROOST_PP_SEQ_ENUM_95(x) x, ROOST_PP_SEQ_ENUM_94
# define ROOST_PP_SEQ_ENUM_96(x) x, ROOST_PP_SEQ_ENUM_95
# define ROOST_PP_SEQ_ENUM_97(x) x, ROOST_PP_SEQ_ENUM_96
# define ROOST_PP_SEQ_ENUM_98(x) x, ROOST_PP_SEQ_ENUM_97
# define ROOST_PP_SEQ_ENUM_99(x) x, ROOST_PP_SEQ_ENUM_98
# define ROOST_PP_SEQ_ENUM_100(x) x, ROOST_PP_SEQ_ENUM_99
# define ROOST_PP_SEQ_ENUM_101(x) x, ROOST_PP_SEQ_ENUM_100
# define ROOST_PP_SEQ_ENUM_102(x) x, ROOST_PP_SEQ_ENUM_101
# define ROOST_PP_SEQ_ENUM_103(x) x, ROOST_PP_SEQ_ENUM_102
# define ROOST_PP_SEQ_ENUM_104(x) x, ROOST_PP_SEQ_ENUM_103
# define ROOST_PP_SEQ_ENUM_105(x) x, ROOST_PP_SEQ_ENUM_104
# define ROOST_PP_SEQ_ENUM_106(x) x, ROOST_PP_SEQ_ENUM_105
# define ROOST_PP_SEQ_ENUM_107(x) x, ROOST_PP_SEQ_ENUM_106
# define ROOST_PP_SEQ_ENUM_108(x) x, ROOST_PP_SEQ_ENUM_107
# define ROOST_PP_SEQ_ENUM_109(x) x, ROOST_PP_SEQ_ENUM_108
# define ROOST_PP_SEQ_ENUM_110(x) x, ROOST_PP_SEQ_ENUM_109
# define ROOST_PP_SEQ_ENUM_111(x) x, ROOST_PP_SEQ_ENUM_110
# define ROOST_PP_SEQ_ENUM_112(x) x, ROOST_PP_SEQ_ENUM_111
# define ROOST_PP_SEQ_ENUM_113(x) x, ROOST_PP_SEQ_ENUM_112
# define ROOST_PP_SEQ_ENUM_114(x) x, ROOST_PP_SEQ_ENUM_113
# define ROOST_PP_SEQ_ENUM_115(x) x, ROOST_PP_SEQ_ENUM_114
# define ROOST_PP_SEQ_ENUM_116(x) x, ROOST_PP_SEQ_ENUM_115
# define ROOST_PP_SEQ_ENUM_117(x) x, ROOST_PP_SEQ_ENUM_116
# define ROOST_PP_SEQ_ENUM_118(x) x, ROOST_PP_SEQ_ENUM_117
# define ROOST_PP_SEQ_ENUM_119(x) x, ROOST_PP_SEQ_ENUM_118
# define ROOST_PP_SEQ_ENUM_120(x) x, ROOST_PP_SEQ_ENUM_119
# define ROOST_PP_SEQ_ENUM_121(x) x, ROOST_PP_SEQ_ENUM_120
# define ROOST_PP_SEQ_ENUM_122(x) x, ROOST_PP_SEQ_ENUM_121
# define ROOST_PP_SEQ_ENUM_123(x) x, ROOST_PP_SEQ_ENUM_122
# define ROOST_PP_SEQ_ENUM_124(x) x, ROOST_PP_SEQ_ENUM_123
# define ROOST_PP_SEQ_ENUM_125(x) x, ROOST_PP_SEQ_ENUM_124
# define ROOST_PP_SEQ_ENUM_126(x) x, ROOST_PP_SEQ_ENUM_125
# define ROOST_PP_SEQ_ENUM_127(x) x, ROOST_PP_SEQ_ENUM_126
# define ROOST_PP_SEQ_ENUM_128(x) x, ROOST_PP_SEQ_ENUM_127
# define ROOST_PP_SEQ_ENUM_129(x) x, ROOST_PP_SEQ_ENUM_128
# define ROOST_PP_SEQ_ENUM_130(x) x, ROOST_PP_SEQ_ENUM_129
# define ROOST_PP_SEQ_ENUM_131(x) x, ROOST_PP_SEQ_ENUM_130
# define ROOST_PP_SEQ_ENUM_132(x) x, ROOST_PP_SEQ_ENUM_131
# define ROOST_PP_SEQ_ENUM_133(x) x, ROOST_PP_SEQ_ENUM_132
# define ROOST_PP_SEQ_ENUM_134(x) x, ROOST_PP_SEQ_ENUM_133
# define ROOST_PP_SEQ_ENUM_135(x) x, ROOST_PP_SEQ_ENUM_134
# define ROOST_PP_SEQ_ENUM_136(x) x, ROOST_PP_SEQ_ENUM_135
# define ROOST_PP_SEQ_ENUM_137(x) x, ROOST_PP_SEQ_ENUM_136
# define ROOST_PP_SEQ_ENUM_138(x) x, ROOST_PP_SEQ_ENUM_137
# define ROOST_PP_SEQ_ENUM_139(x) x, ROOST_PP_SEQ_ENUM_138
# define ROOST_PP_SEQ_ENUM_140(x) x, ROOST_PP_SEQ_ENUM_139
# define ROOST_PP_SEQ_ENUM_141(x) x, ROOST_PP_SEQ_ENUM_140
# define ROOST_PP_SEQ_ENUM_142(x) x, ROOST_PP_SEQ_ENUM_141
# define ROOST_PP_SEQ_ENUM_143(x) x, ROOST_PP_SEQ_ENUM_142
# define ROOST_PP_SEQ_ENUM_144(x) x, ROOST_PP_SEQ_ENUM_143
# define ROOST_PP_SEQ_ENUM_145(x) x, ROOST_PP_SEQ_ENUM_144
# define ROOST_PP_SEQ_ENUM_146(x) x, ROOST_PP_SEQ_ENUM_145
# define ROOST_PP_SEQ_ENUM_147(x) x, ROOST_PP_SEQ_ENUM_146
# define ROOST_PP_SEQ_ENUM_148(x) x, ROOST_PP_SEQ_ENUM_147
# define ROOST_PP_SEQ_ENUM_149(x) x, ROOST_PP_SEQ_ENUM_148
# define ROOST_PP_SEQ_ENUM_150(x) x, ROOST_PP_SEQ_ENUM_149
# define ROOST_PP_SEQ_ENUM_151(x) x, ROOST_PP_SEQ_ENUM_150
# define ROOST_PP_SEQ_ENUM_152(x) x, ROOST_PP_SEQ_ENUM_151
# define ROOST_PP_SEQ_ENUM_153(x) x, ROOST_PP_SEQ_ENUM_152
# define ROOST_PP_SEQ_ENUM_154(x) x, ROOST_PP_SEQ_ENUM_153
# define ROOST_PP_SEQ_ENUM_155(x) x, ROOST_PP_SEQ_ENUM_154
# define ROOST_PP_SEQ_ENUM_156(x) x, ROOST_PP_SEQ_ENUM_155
# define ROOST_PP_SEQ_ENUM_157(x) x, ROOST_PP_SEQ_ENUM_156
# define ROOST_PP_SEQ_ENUM_158(x) x, ROOST_PP_SEQ_ENUM_157
# define ROOST_PP_SEQ_ENUM_159(x) x, ROOST_PP_SEQ_ENUM_158
# define ROOST_PP_SEQ_ENUM_160(x) x, ROOST_PP_SEQ_ENUM_159
# define ROOST_PP_SEQ_ENUM_161(x) x, ROOST_PP_SEQ_ENUM_160
# define ROOST_PP_SEQ_ENUM_162(x) x, ROOST_PP_SEQ_ENUM_161
# define ROOST_PP_SEQ_ENUM_163(x) x, ROOST_PP_SEQ_ENUM_162
# define ROOST_PP_SEQ_ENUM_164(x) x, ROOST_PP_SEQ_ENUM_163
# define ROOST_PP_SEQ_ENUM_165(x) x, ROOST_PP_SEQ_ENUM_164
# define ROOST_PP_SEQ_ENUM_166(x) x, ROOST_PP_SEQ_ENUM_165
# define ROOST_PP_SEQ_ENUM_167(x) x, ROOST_PP_SEQ_ENUM_166
# define ROOST_PP_SEQ_ENUM_168(x) x, ROOST_PP_SEQ_ENUM_167
# define ROOST_PP_SEQ_ENUM_169(x) x, ROOST_PP_SEQ_ENUM_168
# define ROOST_PP_SEQ_ENUM_170(x) x, ROOST_PP_SEQ_ENUM_169
# define ROOST_PP_SEQ_ENUM_171(x) x, ROOST_PP_SEQ_ENUM_170
# define ROOST_PP_SEQ_ENUM_172(x) x, ROOST_PP_SEQ_ENUM_171
# define ROOST_PP_SEQ_ENUM_173(x) x, ROOST_PP_SEQ_ENUM_172
# define ROOST_PP_SEQ_ENUM_174(x) x, ROOST_PP_SEQ_ENUM_173
# define ROOST_PP_SEQ_ENUM_175(x) x, ROOST_PP_SEQ_ENUM_174
# define ROOST_PP_SEQ_ENUM_176(x) x, ROOST_PP_SEQ_ENUM_175
# define ROOST_PP_SEQ_ENUM_177(x) x, ROOST_PP_SEQ_ENUM_176
# define ROOST_PP_SEQ_ENUM_178(x) x, ROOST_PP_SEQ_ENUM_177
# define ROOST_PP_SEQ_ENUM_179(x) x, ROOST_PP_SEQ_ENUM_178
# define ROOST_PP_SEQ_ENUM_180(x) x, ROOST_PP_SEQ_ENUM_179
# define ROOST_PP_SEQ_ENUM_181(x) x, ROOST_PP_SEQ_ENUM_180
# define ROOST_PP_SEQ_ENUM_182(x) x, ROOST_PP_SEQ_ENUM_181
# define ROOST_PP_SEQ_ENUM_183(x) x, ROOST_PP_SEQ_ENUM_182
# define ROOST_PP_SEQ_ENUM_184(x) x, ROOST_PP_SEQ_ENUM_183
# define ROOST_PP_SEQ_ENUM_185(x) x, ROOST_PP_SEQ_ENUM_184
# define ROOST_PP_SEQ_ENUM_186(x) x, ROOST_PP_SEQ_ENUM_185
# define ROOST_PP_SEQ_ENUM_187(x) x, ROOST_PP_SEQ_ENUM_186
# define ROOST_PP_SEQ_ENUM_188(x) x, ROOST_PP_SEQ_ENUM_187
# define ROOST_PP_SEQ_ENUM_189(x) x, ROOST_PP_SEQ_ENUM_188
# define ROOST_PP_SEQ_ENUM_190(x) x, ROOST_PP_SEQ_ENUM_189
# define ROOST_PP_SEQ_ENUM_191(x) x, ROOST_PP_SEQ_ENUM_190
# define ROOST_PP_SEQ_ENUM_192(x) x, ROOST_PP_SEQ_ENUM_191
# define ROOST_PP_SEQ_ENUM_193(x) x, ROOST_PP_SEQ_ENUM_192
# define ROOST_PP_SEQ_ENUM_194(x) x, ROOST_PP_SEQ_ENUM_193
# define ROOST_PP_SEQ_ENUM_195(x) x, ROOST_PP_SEQ_ENUM_194
# define ROOST_PP_SEQ_ENUM_196(x) x, ROOST_PP_SEQ_ENUM_195
# define ROOST_PP_SEQ_ENUM_197(x) x, ROOST_PP_SEQ_ENUM_196
# define ROOST_PP_SEQ_ENUM_198(x) x, ROOST_PP_SEQ_ENUM_197
# define ROOST_PP_SEQ_ENUM_199(x) x, ROOST_PP_SEQ_ENUM_198
# define ROOST_PP_SEQ_ENUM_200(x) x, ROOST_PP_SEQ_ENUM_199
# define ROOST_PP_SEQ_ENUM_201(x) x, ROOST_PP_SEQ_ENUM_200
# define ROOST_PP_SEQ_ENUM_202(x) x, ROOST_PP_SEQ_ENUM_201
# define ROOST_PP_SEQ_ENUM_203(x) x, ROOST_PP_SEQ_ENUM_202
# define ROOST_PP_SEQ_ENUM_204(x) x, ROOST_PP_SEQ_ENUM_203
# define ROOST_PP_SEQ_ENUM_205(x) x, ROOST_PP_SEQ_ENUM_204
# define ROOST_PP_SEQ_ENUM_206(x) x, ROOST_PP_SEQ_ENUM_205
# define ROOST_PP_SEQ_ENUM_207(x) x, ROOST_PP_SEQ_ENUM_206
# define ROOST_PP_SEQ_ENUM_208(x) x, ROOST_PP_SEQ_ENUM_207
# define ROOST_PP_SEQ_ENUM_209(x) x, ROOST_PP_SEQ_ENUM_208
# define ROOST_PP_SEQ_ENUM_210(x) x, ROOST_PP_SEQ_ENUM_209
# define ROOST_PP_SEQ_ENUM_211(x) x, ROOST_PP_SEQ_ENUM_210
# define ROOST_PP_SEQ_ENUM_212(x) x, ROOST_PP_SEQ_ENUM_211
# define ROOST_PP_SEQ_ENUM_213(x) x, ROOST_PP_SEQ_ENUM_212
# define ROOST_PP_SEQ_ENUM_214(x) x, ROOST_PP_SEQ_ENUM_213
# define ROOST_PP_SEQ_ENUM_215(x) x, ROOST_PP_SEQ_ENUM_214
# define ROOST_PP_SEQ_ENUM_216(x) x, ROOST_PP_SEQ_ENUM_215
# define ROOST_PP_SEQ_ENUM_217(x) x, ROOST_PP_SEQ_ENUM_216
# define ROOST_PP_SEQ_ENUM_218(x) x, ROOST_PP_SEQ_ENUM_217
# define ROOST_PP_SEQ_ENUM_219(x) x, ROOST_PP_SEQ_ENUM_218
# define ROOST_PP_SEQ_ENUM_220(x) x, ROOST_PP_SEQ_ENUM_219
# define ROOST_PP_SEQ_ENUM_221(x) x, ROOST_PP_SEQ_ENUM_220
# define ROOST_PP_SEQ_ENUM_222(x) x, ROOST_PP_SEQ_ENUM_221
# define ROOST_PP_SEQ_ENUM_223(x) x, ROOST_PP_SEQ_ENUM_222
# define ROOST_PP_SEQ_ENUM_224(x) x, ROOST_PP_SEQ_ENUM_223
# define ROOST_PP_SEQ_ENUM_225(x) x, ROOST_PP_SEQ_ENUM_224
# define ROOST_PP_SEQ_ENUM_226(x) x, ROOST_PP_SEQ_ENUM_225
# define ROOST_PP_SEQ_ENUM_227(x) x, ROOST_PP_SEQ_ENUM_226
# define ROOST_PP_SEQ_ENUM_228(x) x, ROOST_PP_SEQ_ENUM_227
# define ROOST_PP_SEQ_ENUM_229(x) x, ROOST_PP_SEQ_ENUM_228
# define ROOST_PP_SEQ_ENUM_230(x) x, ROOST_PP_SEQ_ENUM_229
# define ROOST_PP_SEQ_ENUM_231(x) x, ROOST_PP_SEQ_ENUM_230
# define ROOST_PP_SEQ_ENUM_232(x) x, ROOST_PP_SEQ_ENUM_231
# define ROOST_PP_SEQ_ENUM_233(x) x, ROOST_PP_SEQ_ENUM_232
# define ROOST_PP_SEQ_ENUM_234(x) x, ROOST_PP_SEQ_ENUM_233
# define ROOST_PP_SEQ_ENUM_235(x) x, ROOST_PP_SEQ_ENUM_234
# define ROOST_PP_SEQ_ENUM_236(x) x, ROOST_PP_SEQ_ENUM_235
# define ROOST_PP_SEQ_ENUM_237(x) x, ROOST_PP_SEQ_ENUM_236
# define ROOST_PP_SEQ_ENUM_238(x) x, ROOST_PP_SEQ_ENUM_237
# define ROOST_PP_SEQ_ENUM_239(x) x, ROOST_PP_SEQ_ENUM_238
# define ROOST_PP_SEQ_ENUM_240(x) x, ROOST_PP_SEQ_ENUM_239
# define ROOST_PP_SEQ_ENUM_241(x) x, ROOST_PP_SEQ_ENUM_240
# define ROOST_PP_SEQ_ENUM_242(x) x, ROOST_PP_SEQ_ENUM_241
# define ROOST_PP_SEQ_ENUM_243(x) x, ROOST_PP_SEQ_ENUM_242
# define ROOST_PP_SEQ_ENUM_244(x) x, ROOST_PP_SEQ_ENUM_243
# define ROOST_PP_SEQ_ENUM_245(x) x, ROOST_PP_SEQ_ENUM_244
# define ROOST_PP_SEQ_ENUM_246(x) x, ROOST_PP_SEQ_ENUM_245
# define ROOST_PP_SEQ_ENUM_247(x) x, ROOST_PP_SEQ_ENUM_246
# define ROOST_PP_SEQ_ENUM_248(x) x, ROOST_PP_SEQ_ENUM_247
# define ROOST_PP_SEQ_ENUM_249(x) x, ROOST_PP_SEQ_ENUM_248
# define ROOST_PP_SEQ_ENUM_250(x) x, ROOST_PP_SEQ_ENUM_249
# define ROOST_PP_SEQ_ENUM_251(x) x, ROOST_PP_SEQ_ENUM_250
# define ROOST_PP_SEQ_ENUM_252(x) x, ROOST_PP_SEQ_ENUM_251
# define ROOST_PP_SEQ_ENUM_253(x) x, ROOST_PP_SEQ_ENUM_252
# define ROOST_PP_SEQ_ENUM_254(x) x, ROOST_PP_SEQ_ENUM_253
# define ROOST_PP_SEQ_ENUM_255(x) x, ROOST_PP_SEQ_ENUM_254
# define ROOST_PP_SEQ_ENUM_256(x) x, ROOST_PP_SEQ_ENUM_255
#
# else
#
# include <roost/preprocessor/config/limits.hpp>
#
# if ROOST_PP_LIMIT_SEQ == 256
# include <roost/preprocessor/seq/limits/enum_256.hpp>
# elif ROOST_PP_LIMIT_SEQ == 512
# include <roost/preprocessor/seq/limits/enum_256.hpp>
# include <roost/preprocessor/seq/limits/enum_512.hpp>
# elif ROOST_PP_LIMIT_SEQ == 1024
# include <roost/preprocessor/seq/limits/enum_256.hpp>
# include <roost/preprocessor/seq/limits/enum_512.hpp>
# include <roost/preprocessor/seq/limits/enum_1024.hpp>
# else
# error Incorrect value for the ROOST_PP_LIMIT_SEQ limit
# endif
#
# endif
#
# endif
